### ISSUE TITLE
JPL Horizons' query epoch input

### ISSUE THREAD

**Issue by shbhuk** [astropy/astroquery#1590] opened 2019-11-22 15:09 UTC
Hi,
Thanks for the great API to the Horizons web interface. 
One correction that should be made to the documentation is the time format the Horizon's interface likes to be queried in - 

See note below - 
https://ssd.jpl.nasa.gov/?horizons_doc#time
_For cartesian coordinates or osculating elements tables, only TDB may be used. For "observer tables", output may be either UT or TT. TO CHANGE THE UT DEFAULT for observer tables, append a "TT" when entering START time. To switch back, append a "UT" to the start time._

This does not match the note on the Astropy page - 
https://astroquery.readthedocs.io/en/latest/jplhorizons/jplhorizons.html
_Note that all input epochs, both calendar dates/times and Julian Dates, refer to UTC._ 

Let me know if I am interpreting this incorrectly. 

====

Secondly, the query does not like an ISOT input either and fails with the error message - 
`ValueError: Query failed without error message; check URI for more information`

One could check the URI, but that often isn't the most helpful either, and this took me a while to figure out. 

Perhaps, before calling the Horizons API, the Time object could convert it to JD and TDB by default?

For example: 
```
from astropy.time import Time
from astroquery.jplhorizons import Horizons

JDUTC = Time('2012-01-05T00:00:0', format = 'isot', scale='utc')
TargetObj1 = Horizons(id='0', location='@399', epochs=JDUTC, id_type=HorizonsID_type).vectors(refplane='earth') # This gives me an error since it is natively in ISOT.

TargetObj1 = Horizons(id='0', location='@399', epochs=JDUTC.jd, id_type=HorizonsID_type).vectors(refplane='earth') # This runs fine. 

```

astroquery 0.3.10.dev0
astropy 3.2.3

**Comment by bsipocz** [comment] 2020-01-23 23:04
cc @mommermi

**Comment by mommermi** [comment] 2020-01-31 21:40
Thanks, @shbhuk, for pointing this out. #1629 fixes the documentation as you suggested. For the second part of your request, I would like to refer to #1506. Unfortunately, I don't have time to deal with this now...

**Comment by shbhuk** [comment] 2020-01-31 22:11
Thanks!

**Comment by bsipocz** [comment] 2022-12-15 18:57
I would close this as a duplicate of https://github.com/astropy/astroquery/issues/1506

**Closed by bsipocz** 2022-12-15 18:57 UTC
Labels: jplhorizons
