### ISSUE TITLE
astroquery/skyview unit bug

### ISSUE THREAD

**Issue by AstroJacobLi** [astropy/astroquery#2908] opened 2023-12-24 20:32 UTC
Hi there! Now `astropy.units` cannot be used as a bool variable (https://github.com/astropy/astropy/pull/14124). So one will get the following error when passing `width` and `height` to [`SkyView.get_images`](https://github.com/astropy/astroquery/blob/9387c450137dd6ed0f9c2c96df4abfcf201059a8/astroquery/skyview/core.py#L254). 

It's easy to fix, just changing `elif width and height` to `elif (width is not None) and (height is not None)`.

```
File /projects/HSC/LSST/stack_20220527/conda/envs/lsst-scipipe-4.0.0/lib/python3.10/site-packages/astroquery/skyview/core.py:254, in SkyViewClass.get_image_list(self, position, survey, coordinates, projection, pixels, scaling, sampler, resolver, deedger, lut, grid, gridlabels, radius, width, height, cache)
    252 if radius is not None:
    253     size_deg = str(radius.to(u.deg).value)
--> 254 elif width and height:
    255     size_deg = "{0},{1}".format(width.to(u.deg).value,
    256                                 height.to(u.deg).value)
    257 elif width and height:

File ~/.local/lib/python3.10/site-packages/astropy/units/quantity.py:1334, in Quantity.__bool__(self)
   1330 def __bool__(self):
   1331     """This method raises ValueError, since truthiness of quantities is ambiguous,
   1332     especially for logarithmic units and temperatures. Use explicit comparisons.
   1333     """
-> 1334     raise ValueError(
   1335         f"{type(self).__name__} truthiness is ambiguous, especially for logarithmic units"
   1336         " and temperatures. Use explicit comparisons."
   1337     )

ValueError: Quantity truthiness is ambiguous, especially for logarithmic units and temperatures. Use explicit comparisons.
```
Thanks!

**Comment by bsipocz** [comment] 2024-01-09 02:08
duplicate of https://github.com/astropy/astroquery/issues/2756, so I'm closing this for now. A fix is coming for this soon as we already have two PRs for the module.

**Closed by bsipocz** 2024-01-09 02:08 UTC
Labels: bug, duplicate, skyview
