### ISSUE TITLE
fix query hang-up bug in `astroquery.mast`

### ISSUE THREAD

**Issue by jaymedina** [astropy/astroquery#2269] opened 2022-01-31 19:26 UTC
It seems that when 1 or more results are expected from a query, the communication to the MAST API gets hung up. 
So far this seems to only be an issue with query_criteria. Example cases:
`observations = Observations.query_criteria('M1', radius=0.0, obs_collection='GALEX')`
`Observations.query_criteria('M1', radius=0.0, obs_collection='HLA')`

----

An example where I'm retrieving the # of results with query_criteria_count, I see this: 

```
Observations.query_criteria_count('M1', radius=0.0, provenance_name='AIS')
Out: 62992
```

But results on MAST portal show 1:
![image](https://user-images.githubusercontent.com/32107699/151864749-1f903392-898f-4ba2-8a67-dc14fca0de16.png)

**Comment by jaymedina** [comment] 2022-01-31 20:25
Solved: User needs to specify `objectname` if that is one of the parameters being fed:
`Observations.query_criteria_count(objectname='M1', radius=0.0, provenance_name='AIS')`
`Out: 1` 

Need to tinker behind the scenes to see what astroquery does when it's fed a parameter without the user explicitly saying what the kwarg is, because right now they're just fed as **criteria. Adding the `*` in these functions to make explicit kwargs a requirement should solve this problem.

**Comment by bsipocz** [comment] 2022-01-31 20:31
Nice investigation!

I would say keep the issue open even if the cause is found until the code has been fixed.

**Comment by jaymedina** [comment] 2022-01-31 20:32
Sounds good

**Comment by bsipocz** [comment] 2023-08-01 05:46
The original examples now throw a TypeError, e.g. 
``TypeError: ObservationsClass.query_criteria_async() takes 1 positional argument but 2 were given``

So I go ahead and close this.

**Closed by bsipocz** 2023-08-01 05:46 UTC
Labels: bug, mast
