### ISSUE TITLE
Nist query not working anymore

### ISSUE THREAD

**Issue by fmadec** [astropy/astroquery#1349] opened 2019-01-31 10:08 UTC
astroquery.test(package="nist", remote_data=True) failed
```
=========================================================== test session starts ===========================================================
platform linux -- Python 3.6.7, pytest-3.5.0, py-1.5.3, pluggy-0.6.0

Running tests with astroquery version 0.3.9.
Running tests in /software/conda/lib/python3.6/site-packages/astroquery/nist.

Date: 2019-01-31T10:59:58

Platform: Linux-4.9.0-8-amd64-x86_64-with-debian-9.4

Executable: /software/conda/bin/python

Full Python Version: 
3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.14.3
Matplotlib: 2.2.2
Pandas: 0.22.0
Astropy: 3.1.1
APLpy: not available
pyregion: not available
astropy_helpers: 3.1
Using Astropy options: remote_data: any.

rootdir: /software/conda/lib/python3.6/site-packages/astroquery/nist, inifile:
plugins: remotedata-0.2.0, openfiles-0.2.0, doctestplus-0.1.2, arraydiff-0.3
collected 5 items

../../../../../../../software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist.py ...                              [ 60%]
../../../../../../../software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist_remote.py .F                        [100%]

================================================================ FAILURES =================================================================
___________________________________________________________ TestNist.test_query ___________________________________________________________

self = <astroquery.nist.core.NistClass object at 0x7f2c54241a58>, response = <Response [200]>, verbose = False

    def _parse_result(self, response, verbose=False):
        """
            Parses the results form the HTTP response to `astropy.table.Table`.
    
            Parameters
            ----------
            response : `requests.Response`
                The HTTP response object
    
            Returns
            -------
            table : `astropy.table.Table`
            """
    
        pre_re = re.compile("<pre>(.*)</pre>", flags=re.DOTALL)
        links_re = re.compile(r"<a.*?>\s*(\w+)\s*</a>")
        content = str(response.text)
    
        try:
>           pre = pre_re.findall(content)[0]
E           IndexError: list index out of range

/software/conda/lib/python3.6/site-packages/astroquery/nist/core.py:164: IndexError

During handling of the above exception, another exception occurred:

self = <astroquery.nist.tests.test_nist_remote.TestNist object at 0x7f2c4eaaab00>

    def test_query(self):
>       result = nist.core.Nist.query(4000 * u.nm, 7000 * u.nm)

/software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist_remote.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/software/conda/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py:25: in f
    return self.fn(obj, *args, **kwds)
/software/conda/lib/python3.6/site-packages/astroquery/utils/process_asyncs.py:29: in newmethod
    result = self._parse_result(response, verbose=verbose)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <astroquery.nist.core.NistClass object at 0x7f2c54241a58>, response = <Response [200]>, verbose = False

    def _parse_result(self, response, verbose=False):
        """
            Parses the results form the HTTP response to `astropy.table.Table`.
    
            Parameters
            ----------
            response : `requests.Response`
                The HTTP response object
    
            Returns
            -------
            table : `astropy.table.Table`
            """
    
        pre_re = re.compile("<pre>(.*)</pre>", flags=re.DOTALL)
        links_re = re.compile(r"<a.*?>\s*(\w+)\s*</a>")
        content = str(response.text)
    
        try:
            pre = pre_re.findall(content)[0]
        except IndexError:
>           raise Exception("Result did not contain a table")
E           Exception: Result did not contain a table

/software/conda/lib/python3.6/site-packages/astroquery/nist/core.py:166: Exception
Some tests are known to fail when run from the IPython prompt; especially, but not limited to tests involving logging and warning handling.  Unless you are certain as to the cause of the failure, please check that the failure occurs outside IPython as well.  See http://docs.astropy.org/en/stable/known_issues.html#failing-logging-tests-when-running-the-tests-in-ipython for more information.
============================================================ warnings summary =============================================================
None
  Module already imported so cannot be rewritten: pytest_remotedata
  Module already imported so cannot be rewritten: pytest_openfiles
  Module already imported so cannot be rewritten: pytest_doctestplus
  Module already imported so cannot be rewritten: pytest_arraydiff

tests/test_nist.py::test_query_async
  /software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist.py:32: ResourceWarning: unclosed file <_io.BufferedReader name='/software/conda/lib/python3.6/site-packages/astroquery/nist/tests/data/nist_out.html'>
    content = open(filename, 'rb').read()

tests/test_nist.py::test_query
  /software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist.py:32: ResourceWarning: unclosed file <_io.BufferedReader name='/software/conda/lib/python3.6/site-packages/astroquery/nist/tests/data/nist_out.html'>
    content = open(filename, 'rb').read()

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================================= 1 failed, 4 passed, 6 warnings in 0.53 seconds ==============================================

1
```

**Comment by keflavich** [comment] 2019-01-31 16:44
I can't reproduce this locally.  My test run succeeds.  Last week, NIST was down because of the government shutdown, but your test was run today.

Could you verify that you're still seeing the error?  If you are, could you verify that you can access the NIST web pages via a browser?

```
$ python setup.py test -P nist --remote-data
running test
installing to temporary directory: /private/var/folders/_r/c4nkvmpn4vx6qc91qygz8h740000gr/T/astroquery-test-cxtr2v2c
warning: no files found matching 'CHANGES.rst'
warning: no files found matching 'ez_setup.py'
warning: no files found matching '*.pyx' under directory 'astroquery'
warning: no files found matching '*.c' under directory 'astroquery'
warning: no files found matching '*.pxd' under directory 'astroquery'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no files found matching 'astropy_helpers/ez_setup.py'
warning: no files found matching '*.pyx' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.h' under directory 'astropy_helpers/astropy_helpers'
no previously-included directories found matching 'astropy_helpers/build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

/Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
========================================================================================================== test session starts ===========================================================================================================
platform darwin -- Python 3.6.4, pytest-3.6.0, py-1.5.3, pluggy-0.6.0

Running tests with astroquery version 0.3.10.dev5230_testrun.
Running tests in astroquery/nist docs/nist.

Date: 2019-01-31T09:42:32

Platform: Darwin-13.4.0-x86_64-i386-64bit

Executable: /Users/adam/anaconda/envs/astropy36mpl2/bin/python

Full Python Version:
3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.15.1
Matplotlib: 2.2.2
Pandas: 0.23.4
Astropy: 3.2.dev23515
APLpy: 0.0.dev1079
pyregion: 2.0
astropy_helpers: 2.0.8
Using Astropy options: remote_data: any.

rootdir: /private/var/folders/_r/c4nkvmpn4vx6qc91qygz8h740000gr/T/astroquery-test-cxtr2v2c/lib/python3.6/site-packages, inifile: setup.cfg
plugins: remotedata-0.2.0, openfiles-0.2.0, doctestplus-0.1.2, dependency-0.3.2, arraydiff-0.3, flaky-3.4.0
collected 6 items

astroquery/nist/tests/test_nist.py ...                                                                                                                                                                                             [ 50%]
astroquery/nist/tests/test_nist_remote.py ..                                                                                                                                                                                       [ 83%]
docs/nist/nist.rst .                                                                                                                                                                                                               [100%]
===Flaky Test Report===


===End Flaky Test Report===

======================================================================================================== 6 passed in 3.54 seconds =======================================================================================================
```

**Comment by fmadec** [comment] 2019-02-01 10:22
Yes yersterday it worked via browser.
and it is now working, although I have an other error (reproduced on 2 differents machines)

=========================================================== test session starts ===========================================================
platform linux -- Python 3.6.7, pytest-3.5.0, py-1.5.3, pluggy-0.6.0

Running tests with astroquery version 0.3.9.
Running tests in /software/conda/lib/python3.6/site-packages/astroquery/nist.

Date: 2019-02-01T10:48:40

Platform: Linux-4.9.0-8-amd64-x86_64-with-debian-9.4

Executable: /software/conda/bin/python

Full Python Version: 
3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.14.3
Matplotlib: 2.2.2
Pandas: 0.22.0
Astropy: 3.1.1
APLpy: not available
pyregion: not available
astropy_helpers: 3.1
Using Astropy options: remote_data: any.

rootdir: /software/conda/lib/python3.6/site-packages/astroquery/nist, inifile:
plugins: remotedata-0.2.0, openfiles-0.2.0, doctestplus-0.1.2, arraydiff-0.3
collected 5 items

../../../../../../../software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist.py ...                              [ 60%]
../../../../../../../software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist_remote.py ..                        [100%]

============================================================ warnings summary =============================================================
tests/test_nist.py::test_query_async
  /software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist.py:32: ResourceWarning: unclosed file <_io.BufferedReader name='/software/conda/lib/python3.6/site-packages/astroquery/nist/tests/data/nist_out.html'>
    content = open(filename, 'rb').read()

tests/test_nist.py::test_query
  /software/conda/lib/python3.6/site-packages/astroquery/nist/tests/test_nist.py:32: ResourceWarning: unclosed file <_io.BufferedReader name='/software/conda/lib/python3.6/site-packages/astroquery/nist/tests/data/nist_out.html'>
    content = open(filename, 'rb').read()

tests/test_nist_remote.py::TestNist::()::test_query_async
  /software/conda/lib/python3.6/socket.py:657: ResourceWarning: unclosed <socket.socket fd=51, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.1.1.11', 57808), raddr=('129.6.13.138', 443)>
    self._sock = None

-- Docs: http://doc.pytest.org/en/latest/warnings.html
================================================== 5 passed, 3 warnings in 2.15 seconds ===================================================

0

when I tried a query I got this error:

[Errno 2] No such file or directory: '/tmp/tmp80w8pfebastropy_cache/astropy/astroquery/Nist/b883013857b733aa0f78a6fdf21b970a04c29c35b399aa6f54877616.pickle'

**Comment by keflavich** [comment] 2019-02-01 18:02
OK, the tests pass, which means the original error is gone.

Please show the query you tried that failed.  The message you showed vaguely implies a problem with caching, but we need a lot more information.

**Comment by bsipocz** [comment] 2019-04-03 02:46
I'm closing this. NIST is passing all tests for me. 

@fmadec - feel free to reopen if it's still failing for you even after clearing the cache.

**Closed by bsipocz** 2019-04-03 02:46 UTC
Labels: nist, question
