### ISSUE TITLE
Simbad Query for Magnitudes  - case issue flux(j) versus flux(J) - mismatched field name throughout query

### ISSUE THREAD

**Issue by twotonnetess** [astropy/astroquery#566] opened 2015-08-20 14:27 UTC
Hi all, 

I am trying to query Simbad for JHK and L magnitudes. I have found some issues with cases and mismatched field names between the different steps of querying. 

It took me a while to figure out that instead of adding 
`Simbad.add_votable_fields('flux(j)','flux_bibcode(j)','flux_error(j)','flux_quality(j)')`
it needed to be a 
`Simbad.add_votable_fields('flux(J)','flux_bibcode(j)','flux_error(j)','flux_quality(j)')`

If I do not capitalise the J for the first flux field, I later got an error when I queried simbad 
i.e.  
`simbad_result = Simbad.query_region(kmos_coords,radius=RAD_SEARCH*u.arcsec)`

results in the following error: 

```
    simbad_result = Simbad.query_region(kmos_coords,radius=RAD_SEARCH*u.arcsec)
  File "/software/local/lib64/python2.7/site-packages/astroquery-0.3.dev0-py2.7.egg/astroquery/simbad/core.py", line 445, in query_region
    return self._parse_result(result, SimbadVOTableResult, verbose=verbose)
  File "/software/local/lib64/python2.7/site-packages/astroquery-0.3.dev0-py2.7.egg/astroquery/simbad/core.py", line 743, in _parse_result
    "Exception: " + str(ex))
astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error.  The attempted parsed result is in self.last_parsed_result.
Exception: No table found in VOTABLE file.
```

So capitalising J, H and K gets around this. (even though they are recognised as fields as flux(j) or flux(J)). 
HOWEVER, this does not seem to work for the L band. 

Adding the following fields 
`Simbad.add_votable_fields('flux_bibcode(l)','flux_error(l)','flux_quality(l)')`
works find. 
However, once I add `'flux(L)'` I get the same above error. 

Similarly, there is a re-occurance of mismatched field names in the results tables. 
-> fluxes are simbad_result['FLUX_J'] 
-> errors are  simbad_result['FLUX_ERROR_j']
->  flux_quality does not seem to be returned at all,  i.e, simbad_result['FLUX_QUALITY_J'] or simbad_result['FLUX_QUALITY_j'] does not exist. Indeed does not seem to exist in simbad_result. 
- spectral type changes from votable field sp to simbad_result['SP_TYPE']

So capitalising some of the flux bands was a work around, but no L band fluxes available.

**Comment by keflavich** [comment] 2015-08-20 15:00
There is an error here: astroquery should be capitalizing the flux and checking whether the filters are valid, though that is difficult since they are not listed.  Apparently SIMBAD simply does not list L-band magnitudes: the following script reproduces your error when submitted directly to SIMBAD:
```
votable {main_id,coordinates,flux(L)}
votable open
query coo  19:23:40.05 +14:31:07.1004 radius=5.0s frame=ICRS
votable close
```

**Comment by ManonMarchand** [comment] 2023-09-08 13:52
Hello, 
You can get the list of currently supported bands with 

```python
import pyvo
simbadtap = pyvo.dal.TAPService("https://simbad.cds.unistra.fr/simbad/sim-tap/")
query = "select * from filter"
result = simbadtap.search(query)
```

That gives you the table describing the bands `filter` from simbad. It looks like this:

```
<Table length=14>
  description    filtername  unit 
     object        object   object
---------------- ---------- ------
     Magnitude U          U    mag
     Magnitude B          B    mag
     Magnitude V          V    mag
     Magnitude R          R    mag
     Magnitude I          I    mag
     Magnitude J          J    mag
     Magnitude H          H    mag
     Magnitude K          K    mag
Magnitude SDSS u          u    mag
Magnitude SDSS g          g    mag
Magnitude SDSS r          r    mag
Magnitude SDSS i          i    mag
Magnitude SDSS z          z    mag
Magnitude Gaia G          G    mag
``` 

Astroquery should not capitalize the flux because we have different definitions depending on the case. I'll close this issue as it is not on astroquery's side.

If this does not answer the question, or if it is a request for more filters, feel free to contact us directly (cds-question @ unistra.fr)

**Closed by ManonMarchand** 2023-09-08 13:52 UTC
Labels: simbad
