### ISSUE TITLE
non-J2000 coordinates in SkyView not working?

### ISSUE THREAD

**Issue by kmhess** [astropy/astroquery#2272] opened 2022-02-01 12:58 UTC
I'm using SkyView in astroquery to try and get some simple DSS2 images for plotting radio contours on top.  As I was testing my program, I tried it on some rather old VLA data that was taken in B1950 coordinates.  Rather than try to transform my input coordinates ahead of time, I tried to take advantage of the coordinate keyword in SkyView, but it appears that SkyView fails to retrieve an image for anything other than J2000 or a non-specified coordinates keyword.

```
In [10]: test= SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'])

In [11]: test
Out[11]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x1150b48e0>]]

In [12]: test1= SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'],coordinates='B1950')

In [13]: test1
Out[13]: []

In [14]: test2= SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'],coordinates='J2000')

In [15]: test2
Out[15]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x114c3bac0>]]

In [16]: test3= SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'],coordinates='B1975.5')

In [17]: test3
Out[17]: []

In [18]: test4= SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'],coordinates='J2010.1')

In [19]: test4
Out[19]: []
```

**Comment by keflavich** [comment] 2022-02-01 13:06
@kmhess thanks for reporting this.  I can't reproduce it, though: if I run the same queries, I get results.

What version of astropy are you using?

```python
In [11]: SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'], coordinates='J2000')
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
WARNING: InputWarning: Coordinate string is being interpreted as an ICRS coordinate. [astroquery.utils.commons]
Out[11]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x7fb580d03700>]]

In [12]: SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'], coordinates='J2000.1')
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
WARNING: InputWarning: Coordinate string is being interpreted as an ICRS coordinate. [astroquery.utils.commons]
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv10156115767197.fits
|========================================================================================================================================================================================================================================================| 3.2M/3.2M (100.00%)         1s
Out[12]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x7fb58083e130>]]

In [13]: SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'], coordinates='B1950')
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
WARNING: InputWarning: Coordinate string is being interpreted as an ICRS coordinate. [astroquery.utils.commons]
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv10156132987154.fits
|========================================================================================================================================================================================================================================================| 3.2M/3.2M (100.00%)         1s
Out[13]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x7fb579b43e80>]]

In [14]: SkyView.get_images(position='11h59m29.2885s +30d07m37.671s',width=6*u.arcmin,height=6*u.arcmin,pixels=900,survey=['DSS2 Blue'],coordinates='J2010.1')
    ...:
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
WARNING: InputWarning: Coordinate string is being interpreted as an ICRS coordinate. [astroquery.utils.commons]
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv10156165918409.fits
|========================================================================================================================================================================================================================================================| 3.2M/3.2M (100.00%)         1s
Out[14]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x7fb58085b1f0>]]
```

**Comment by kmhess** [comment] 2022-02-01 14:33
Hm...that's frustrating.

I have python 3.9.7.

My first report was based on:
astropy 4.2.1
astroquery 0.4.1

But I uninstalled both and just ran the test with the same results using:
astropy 5.0.1
astroquery 0.4.5

**Comment by keflavich** [comment] 2022-02-01 14:41
huh, ok.  I tried on another machine and suddenly got no hits, not even for the first one.  I had success with:
astroquery, astropy = `0.4.5.dev7313 5.1.dev424+ga1475dd9a`
but failure with
astroquery, astropy = `0.4.5.dev7175 4.3.1`

So maybe there's still an issue here.

**Comment by keflavich** [comment] 2022-02-01 14:57
OK, this is definitely a server issue: my successes from earlier - on the same machine, in the same ipython session - cannot be replicated.

However, even though this is a server issue (skyview isn't returning results when it should), it is also an astroquery issue: we should be raising errors (if possible) when bad things are returned.

You'll need to clear the cache (or for now just do `cache=False`) and try again; SkyView is intermittently returning results.

**Comment by kmhess** [comment] 2022-02-01 15:00
Okay, thanks for looking into this and for the cache tip!

**Comment by vickyscowcroft** [comment] 2022-02-01 17:39
I'm getting the same issue - skyview isn't returning any results but isn't reporting any errors. I'm using astroquery 0.4.5 and astropy 4.3.1. Clearing the cache and using cache=False haven't made any difference.

**Comment by keflavich** [comment] 2022-02-01 17:43
@vickyscowcroft as noted [above](https://github.com/astropy/astroquery/issues/2272#issuecomment-1026932475), this is a server issue - skyview is not returning data.  Try again; the issue appears to be intermittent (it has changed several times today)

**Comment by kmhess** [comment] 2022-02-16 17:13
> OK, this is definitely a server issue: my successes from earlier - on the same machine, in the same ipython session - cannot be replicated.
> 
> However, even though this is a server issue (skyview isn't returning results when it should), it is also an astroquery issue: we should be raising errors (if possible) when bad things are returned.
> 
> You'll need to clear the cache (or for now just do `cache=False`) and try again; SkyView is intermittently returning results.

I found another "bad thing" that you can catch with an error.  I tried querying for 'GOODS: HST NICMOS' with a position I knew wouldn't work and astroquery crashed out with an HTTPError:

```  File "/Users/hess/SoFiA-image-pipeline/modules/get_ancillary.py", line 16, in get_skyview
    path = SkyView.get_images(position=hi_pos.to_string('hmsdms'), coordinates='ICRS',
  File "/usr/local/lib/python3.9/site-packages/astroquery/skyview/core.py", line 208, in get_images
    return [obj.get_fits() for obj in readable_objects]
  File "/usr/local/lib/python3.9/site-packages/astroquery/skyview/core.py", line 208, in <listcomp>
    return [obj.get_fits() for obj in readable_objects]
  File "/usr/local/lib/python3.9/site-packages/astroquery/utils/commons.py", line 375, in get_fits
    filedata = self.get_string()
  File "/usr/local/lib/python3.9/site-packages/astroquery/utils/commons.py", line 430, in get_string
    raise e
  File "/usr/local/lib/python3.9/site-packages/astroquery/utils/commons.py", line 422, in get_string
    with self._readable_object as f:
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/astropy/utils/data.py", line 267, in get_readable_fileobj
    name_or_obj = download_file(
  File "/usr/local/lib/python3.9/site-packages/astropy/utils/data.py", line 1396, in download_file
    raise errors[sources[0]]
  File "/usr/local/lib/python3.9/site-packages/astropy/utils/data.py", line 1359, in download_file
    f_name = _download_file_from_source(
  File "/usr/local/lib/python3.9/site-packages/astropy/utils/data.py", line 1163, in _download_file_from_source
    with _try_url_open(source_url, timeout=timeout, http_headers=http_headers,
  File "/usr/local/lib/python3.9/site-packages/astropy/utils/data.py", line 1100, in _try_url_open
    return urlopener.open(req, timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by bsipocz** [comment] 2022-12-01 07:46
The original issue seem was a cashing problem, and the cache has been refactored since, as well as got an extended documentation. So I'm closing this issue now.

As, to this last comment above: it looks to be the same as https://github.com/astropy/astroquery/issues/572, and  I'm afraid we can't really do much about the 404 is case of a missing coverage as that 404 is what we receive from the server (and the one you get in the browser, too).

**Closed by bsipocz** 2022-12-01 07:46 UTC
Labels: skyview, cache
