### ISSUE TITLE
Can't login to eso archive

### ISSUE THREAD

**Issue by DanielAndreasen** [astropy/astroquery#902] opened 2017-05-09 14:18 UTC
Hi,

I have tried to login to the eso archive unsuccessfull, and would like some help.
Code used:

    from astroquery.eso import Eso
    eso = Eso()
    eso.login('username')  # I use my actual username here

and I'm left with this error message

    Traceback (most recent call last):
      File "eso_archive.py", line 12, in <module>
        eso.login('dandreasen')
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/astroquery/query.py", line 330, in login
        self._authenticated = self._login(*args, **kwargs)
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/astroquery/eso/core.py", line 219, in _login
        "astroquery:www.eso.org", username)
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/keyring/core.py", line 42, in get_password
        return _keyring_backend.get_password(service_name, username)
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/keyring/backends/SecretService.py", line 51, in get_password
        collection = self.get_default_collection()
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/keyring/backends/SecretService.py", line 43, in get_default_collection
        collection.unlock()
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/secretstorage/collection.py", line 63, in unlock
        return unlock_objects(self.bus, [self.collection_path], callback)
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/secretstorage/util.py", line 168, in unlock_objects
        return exec_prompt_glib(bus, prompt)[0]
      File "/home/daniel/Software/anaconda3/envs/ObservationTools/lib/python2.7/site-packages/secretstorage/util.py", line 127, in exec_prompt_glib
        from gi.repository import GLib
    ImportError: No module named gi.repository

As you can see, I use a `Anaconda` enviroment, and that seems to be the root of all my problems.

If I try this outside a fresh conda enviroment (I basically have to install some python packages the old-school way since it is not on pip) I can progress, until I reach an error again.

    Traceback (most recent call last):
      File "eso_archive.py", line 7, in <module>
        from astroquery.eso import Eso
      File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/astroquery/__init__.py", line 12, in <module>
        from ._astropy_init import *
      File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/astroquery/_astropy_init.py", line 120, in <module>
        import astropy.config.configuration as config
    ImportError: No module named astropy.config.configuration

Any help to progress is highly appreciated.

**Comment by keflavich** [comment] 2017-05-09 14:34
I have no idea what's gone wrong here, but my suggestion would be to reinstall keyring with conda, then reinstall astropy into that conda environment and try again.  These things just... shouldn't happen.

**Comment by DanielAndreasen** [comment] 2017-05-09 15:32
I manage to make it run on another computer. Not sure why it works there.
Here were some things I had to install (on a Debian based OS)

    sudo apt-get install libffi-dev libssl-dev libxml2-dev libxslt1-dev python-dev libdbus-1-dev libdbus-glib-1-dev

and from `pip` I installed the following

    pip install dbus-python

**Comment by DanielAndreasen** [comment] 2017-05-10 09:47
I manage to make it run on another computer. Not sure why it works there.
Here were some things I had to install (on a Debian based OS)

    sudo apt-get install libffi-dev libssl-dev libxml2-dev libxslt1-dev python-dev libdbus-1-dev libdbus-glib-1-dev

and from `pip` I installed the following

    pip install dbus-python

**Comment by DanielAndreasen** [comment] 2017-05-10 09:49
I made some more progress. Got an encoding error from `html5lib`. Following the description [here](http://stackoverflow.com/questions/39086278/html5lib-typeerror-init-got-an-unexpected-keyword-argument-encoding) fixed it.

    pip install -U html5lib=="0.9999999"

Currently having a `IndexError` when `eso.query_instrument('crires', column_filter={'target': 'HD20010'})` but will keep working on this.

**Comment by DanielAndreasen** [comment] 2017-05-10 10:42
Still progressing. I have some problems when reading the form. The fix, which works for me is to change `form_id='queryset'` to `form_id=None` in [line 436](https://github.com/astropy/astroquery/blob/master/astroquery/eso/core.py#L436).

**Comment by keflavich** [comment] 2017-05-16 03:08
Are you still having problems with just logging in?  I am still able to without any changes to the form.

**Comment by DanielAndreasen** [comment] 2017-05-16 07:48
No problems with logging in, but still need to change the form (didn't work more on this since the last message).
I am not sure exactly what fixed the problem, but I have tried sharing as many informations as possible if others will have similar problems.

**Comment by bsipocz** [comment] 2017-05-16 10:55
@DanielAndreasen - Since your login issue is solved I'm in favour of closing this.

However before doing so, could you post a minimal failing example, so we could try to reproduce the issue you see? If it's a bug we can open another issue for it, if not maybe we can help you either here on gitter to solve it.

**Comment by DanielAndreasen** [comment] 2017-05-16 14:07
I agree with you. Here is a minimal example:

    eso = Eso()
    eso.login(username, store_password=args.store_password)
    table = eso.query_instrument('crires', column_filters={'target': 'HD20010'})
    table.pprint()

I am currently on my other computer and this works fine. It must be some strange configuration of versions that course an error. Probably not python package versions, since I use enviroments to install these.

**Comment by bsipocz** [comment] 2017-05-16 14:37
This works for me, too. So closing this issue. Feel free to reopen/open another one if you bump into issues in astroquery.

**Closed by bsipocz** 2017-05-16 14:37 UTC
Labels: question

**Comment by DanielAndreasen** [comment] 2017-05-16 14:49
Will do. Thanks for your time :smile:
