### ISSUE TITLE
SDSS incorrect server link

### ISSUE THREAD

**Issue by balashev** [astropy/astroquery#2219] opened 2021-11-17 13:32 UTC
Hello,

I encountered errors when trying to download quasar spectra using astroquery.sdss 

It seems that broken links are generated when astroquery tries to download from sdss database, and "urllib.error.HTTPError: HTTP Error 404: Not Found" is generated.

For example, asking for (J130709.97+302818.71)

astroquery generates:
https://data.sdss.org/sas/dr14/boss/spectro/redux/v5_10_0/spectra/8276/spec-8276-57067-0092.fits,

while it should be 
https://data.sdss.org/sas/dr14/eboss/spectro/redux/v5_10_0/spectra/8276/spec-8276-57067-0092.fits

where BOSS --> EBOSS.

The similar things are also happen for asking dr16 objects, either by coordinates or by plate-mjd-fiberID. For example, asking for SDSS.get_spectra(plate=9403,mjd=58018,fiberID=485) return None

Can anyone update the generation of the links in astroquery.SDSS to include the latest EBOSS releases?

**Comment by keflavich** [comment] 2021-11-17 14:06
this is solved by #2214 and is a duplicate of #1731.

**Comment by balashev** [comment] 2021-11-17 15:54
There is still a problem to load spectra from DR16 data release since it needs to add '/lite' of '/full' in the link address which is not supported by previous data releases.

**Comment by keflavich** [comment] 2021-11-17 16:02
OK that sounds like potentially a new issue.  I see in #2214 that `/full` is added, but `/lite` is not.  @weaverba137 can you comment?

**Comment by keflavich** [comment] 2021-11-17 16:04
Right, you've already commented on #2214 - let's keep discussion centralized there.  I'm closing this again in favor of #2214 - we should handle both issues in one place.

**Closed by keflavich** 2021-11-17 16:04 UTC
Labels: sdss
