### ISSUE TITLE
Issue with ALMA finder chart function: parameters not accepted by ALMA service

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroquery#889] opened 2017-04-17 10:40 UTC
The following example:

```python
from astroquery.alma import make_finder_chart
from astropy import units as u
make_finder_chart('M31', 2 * u.arcmin, 'm31')
```

results in the following error (with Python 3):

```
INFO: Querying <bound method SkyViewClass.get_images of <astroquery.skyview.core.SkyViewClass object at 0x113a16208>> for images [astroquery.alma.utils]
INFO: Querying ALMA around M31 [astroquery.alma.utils]
Traceback (most recent call last):
  File "chart.py", line 4, in <module>
    make_finder_chart('M31', 2 * u.arcmin, 'm31')
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/alma/utils.py", line 175, in make_finder_chart
    **kwargs)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/alma/utils.py", line 212, in make_finder_chart_from_image
    **alma_kwargs)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/alma/core.py", line 106, in query_region_async
    science=science, **kwargs)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/alma/core.py", line 137, in query_async
    self.validate_query(payload)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/alma/core.py", line 156, in validate_query
    self._validate_payload(payload)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/astroquery/alma/core.py", line 813, in _validate_payload
    " {0}".format(invalid_params))
astroquery.exceptions.InvalidQueryError: The following parameters are not accepted by the ALMA query service: ['ra_dec', 'result_view']
```

**Comment by astrofrog** [comment] 2017-04-17 10:57
This seems to be a non-detemrministic issue, it seems to occur in about half of queries.

**Comment by keflavich** [comment] 2017-04-17 12:16
Yes, I've been encountering this a lot while working on #888 and #881.  I think the ALMA servers are just very flaky, and slightly malicious.  The problem is, sometimes they will return a response with *completely blank* content, but with HTTP code 200, which isn't really right.

Also, see https://github.com/astropy/astroquery/pull/888/files#diff-6d3cd6fd34e31469aa220e5eecdf05f1R873 for a partial "fix".

**Comment by bsipocz** [comment] 2022-11-18 06:17
alma `make_finder_chart` has been deprecated and removed, closing this now.

**Closed by bsipocz** 2022-11-18 06:17 UTC
Labels: bug, alma
