### ISSUE TITLE
MNT: Remove Python 2 code

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#1667] opened 2020-03-05 15:39 UTC
Things like `from __future__ import ...`, `six`, `class MyClass(object)`, and so on.

p.s. I thought we had an issue for this but I cannot find it. If this is a duplicate, feel free to close.

**Comment by bsipocz** [comment] 2020-03-05 16:37
I started to work on it locally, ETA is for 4.0 when we switch infrastructure. Hopefully sooner, but we definitely need to get it done by 4.0

**Comment by pllim** [comment] 2020-03-05 16:39
You mean 1.0?

**Comment by bsipocz** [comment] 2020-03-05 16:41
no, we agreed to call it 4.0 :)

see #1604

**Comment by daisycodes** [comment] 2020-10-16 12:16
@bsipocz is this across the repo or just a specific module? Asking because of the tag *MNT* in the ticket title. Also do we want to split this? I would love to submit a PR on this but seems this might be a big one and might take a while to completely review. I did a `2to3 astroquery` on the repo and the diff it generated is kind of huge.

**Comment by daisycodes** [comment] 2020-10-16 12:17
Oh wait, this might not be as big as I thought. Just realized `2to3` was also refactoring files inside my virtual environment. I think that's why the diff was huge.

**Comment by bsipocz** [comment] 2021-11-01 21:38
#1870 is a duplicate of this issue, but I would go ahead and keep that one open as the checklist in that one may be useful for people to see what needs to be picked up. Thanks!

**Closed by bsipocz** 2021-11-01 21:38 UTC
Labels: package-intermediate, refactor

**Comment by pllim** [comment] 2021-11-03 13:28
Sounds good to me. Thanks!

p.s. Why did they change the color of closed _issue_ from red to purple? It really messes with my head.
