### ISSUE TITLE
ALMA query having issues with various columns, plus missing abstract

### ISSUE THREAD

**Issue by alvaroribas** [astropy/astroquery#879] opened 2017-03-31 23:08 UTC
ALMA query seems to fail to properly retrieve things such as band names (and probably other columns), probably due to some changes introduced in the ALMA archive. As an example

```
In [27]: query = Alma.query_object('M33')

In [28]: query = Alma.query_object('M33')
# check length of query
In [29]: print(len(query))
67

# check band of the first element
In [31]: print(query[0]['Band'])
b'\xf1'
# try decoding?
In [32]: print(bytes.decode(query[0]['Band']))
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-32-175ff92f0e8b> in <module>()
----> 1 print(bytes.decode(query[0]['Band']))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 0: unexpected end of data
```
This problem may affect other columns in the query too.

Additionally, the abstract of the projects is no longer among the columns, which would be good to add again if possible.

**Comment by keflavich** [comment] 2017-03-31 23:11
This was supposed to be fixed by https://github.com/astropy/astroquery/pull/775, but since it still appears here, I'll need a new fix.

The best workaround for the moment is to print everything except the Band entry.  The problem is upstream: the ALMA archive is still incorrectly encoding that entry in the votable.

The lack of an abstract may be an upstream issue too....

**Comment by keflavich** [comment] 2017-03-31 23:54
@alvaroribas are you using the latest version of astroquery?  I cannot reproduce this issue

**Comment by alvaroribas** [comment] 2017-04-01 03:00
I have to apologize, for some reason that I don't totally understand, running:
`conda update astropy`
`conda update astroquery`
did not update to the latest version, and I had to run:
`conda install -c astropy astroquery`

With the new version, the problem with the bands is fixed. On the other hand, the project code seems to be broken now...
Regarding the abstract, I know they changed how it is displayed in the archive (now it appears when placing the cursor over the project code). Not sure if it can be fixed though.

**Comment by bsipocz** [comment] 2017-04-01 10:19
@alvaroribas - astroquery is not in the default conda channel but on the astropy channel, thus you always need to specify the channel, or add it to your config.

**Comment by keflavich** [comment] 2017-04-01 13:14
Huh, yes, I see the missing project code.  This is a new problem...

**Comment by bsipocz** [comment] 2021-11-02 09:02
@keflavich - is this still relevant, given that a lot has happened in the alma module and with the upstream API since this was opened? I don't see a `Band` column any more, but there is a `band_list`, that seems to be encoded properly (though I suppose it should be an int column instead of a str). Also, I see both `'pub_abstract'` and `'proposal_abstract'` columns, but no project code. So, overall a lot has changes, but I still suppose the issue has been resolved.

**Comment by bsipocz** [comment] 2021-11-02 09:03
(oops, I didn't mean to close it yet)

**Comment by keflavich** [comment] 2021-11-02 12:41
No, this isn't direct relevant any more

**Closed by keflavich** 2021-11-02 12:41 UTC
Labels: alma, close?
