### ISSUE TITLE
jplhorizons Horizons query fails when tried with many epochs

### ISSUE THREAD

**Issue by ysBach** [astropy/astroquery#1496] opened 2019-06-27 09:11 UTC
When I query more than 419 epochs, the following error appears:
```ValueError: Query failed without error message; check URI for more information```

```python
epoch_ref = Time(2450000, format='jd')
epochs = epoch_ref + np.arange(0, 419) * u.day
obj = Horizons(id=111, epochs=epochs.jd)
eph = obj.ephemerides()
```
When I change to ``np.arange(0, 420)`` for ``epochs``, I got the above ``ValueError``. But such a "maximum" number of allowed epochs seems to change every time and I couldn't find a rule.

I experienced the issue since about a year ago when I used ``callhorizons``, and I just made a simple module in my custom photometry package to chop the data into chunks of 100 epochs and query separately, because after numerous tests, I found the "maximum" number of allowed epochs is not smaller than 100 (back then I used Windows 10 & Ubuntu, and now I use Mac as well as those, so it's not an OS dependent problem).

**Comment by keflavich** [comment] 2019-06-27 14:48
@mommermi - can you look at this?

**Comment by mommermi** [comment] 2019-06-27 15:40
The problem is described [here](https://astroquery.readthedocs.io/en/latest/jplhorizons/jplhorizons.html#keep-queries-short): if you try to query too many epochs, the URI that is sent to the Horizons server is too long and gets truncated - and hence becomes invalid.

Since you are querying equidistant time steps, you should use `epochs={'start': 2450000, 'step': '1d', 'stop': 2450419}`. This will create the output that you would expect - and it allows you to query much more than 419 epochs.

**Comment by ysBach** [comment] 2019-07-07 05:57
@mommermi Thanks for the reply..! I didn't see that doc in the "latest" as I recently was using the v 0.3.9. :)

But it is quite frequent to query more than hundreds of (irregularly sampled) epochs in my case for asteroids light curve analysis, I myself needed to make a simple wrapper which automatically chops the epochs into 100, query for each chunk, and combine the resulting tables.

**Comment by bsipocz** [comment] 2019-07-07 20:18
@ysBach - for astroquery it's very much encouraged to use "latest", and do upgrade with `pip install --pre -U astroquery` regularly, as we do continuous deployment for most of the fixes.

**Comment by bsipocz** [comment] 2022-12-15 19:11
Closing as the discussion above suggested a way to do the query, and there are multiple examples in the docs, too along with the limitations for the query size.

**Closed** 2022-12-15 19:10 UTC
Labels: jplhorizons
