### ISSUE TITLE
SDSS query example breaks

### ISSUE THREAD

**Issue by timothydmorton** [astropy/astroquery#703] opened 2016-06-06 18:26 UTC
Just ran the first SDSS query [example](http://astroquery.readthedocs.io/en/latest/sdss/sdss.html), and it breaks; traceback below.  I'm running astroquery 0.3.1 and astropy 1.1.2.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-7ba462ce82ac> in <module>()
      1 from astroquery.sdss import SDSS
      2 pos = SkyCoord('0h8m05.63s +14d50m23.3s', frame='icrs')
----> 3 SDSS.query_region(pos, spectro=True)

/Users/tdm/anaconda/lib/python2.7/site-packages/astroquery/utils/class_or_instance.pyc in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

/Users/tdm/anaconda/lib/python2.7/site-packages/astroquery/utils/process_asyncs.pyc in newmethod(self, *args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response
---> 29             result = self._parse_result(response, verbose=verbose)
     30             self.table = result
     31             return result

/Users/tdm/anaconda/lib/python2.7/site-packages/astroquery/sdss/core.pyc in _parse_result(self, response, verbose)
    833                                           names=True, dtype=None,
    834                                           delimiter=',', skip_header=1,
--> 835                                           comments='#'))
    836 
    837         if len(arr) == 0:

/Users/tdm/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.pyc in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows)
   1764             # Raise an exception ?
   1765             if invalid_raise:
-> 1766                 raise ValueError(errmsg)
   1767             # Issue a warning ?
   1768             else:

ValueError: Some errors were detected !
    Line #60 (got 4 columns instead of 1)
    Line #122 (got 6 columns instead of 1)
    Line #123 (got 7 columns instead of 1)
    Line #124 (got 4 columns instead of 1)
    Line #125 (got 4 columns instead of 1)
    Line #126 (got 4 columns instead of 1)
    Line #128 (got 2 columns instead of 1)

**Comment by bsipocz** [comment] 2016-06-06 18:36
This is a duplicate of issues #699 and #694.

SDSS's remote API for DR12 changed, but since then we made a fix for astroquery. You can either use the development version, or wait a few days for the new release that will contain the fix.

**Closed by bsipocz** 2016-06-06 18:36 UTC

**Comment by timothydmorton** [comment] 2016-06-07 02:58
OK thanks!
