### ISSUE TITLE
Horizons query fails

### ISSUE THREAD

**Issue by hettlage** [astropy/astroquery#1200] opened 2018-07-14 09:59 UTC
I try to execute the following code with the latest astroquery version installed:

```python
from astroquery.jplhorizons import Horizons
Horizons(id='900034', id_type='id').ephemerides()
```

This gives an error:

```
IOError: Cannot parse table column names.
```

The problem seems to be that the HTTP request to the JPL server returns HTML rather than the expected result.

**Comment by bsipocz** [comment] 2018-07-14 11:19
This is a duplicate of https://github.com/astropy/astroquery/issues/1192 and has been already been fixed in master.

**Closed by bsipocz** 2018-07-14 11:19 UTC

**Comment by hettlage** [comment] 2018-07-14 11:38
Thanks a lot @bsipocz
