### ISSUE TITLE
SSLCertVerificationError found while running an example code of astroquery in a virtual environment

### ISSUE THREAD

**Issue by deepjyotisatpathy18032** [astropy/astroquery#2123] opened 2021-07-27 15:15 UTC
Hello,
I tried running a basic example code using asroquery.gaia which I got from the website, in a virtual environment having python 3.7.0 and the astroquery version 0.4.3. I tried updating astroquery but still I get the same error. Below is the error: 
![Screenshot 2021-07-27 at 3 37 50 AM](https://user-images.githubusercontent.com/61833438/127179579-db26650e-257a-40a4-aba8-9cfc02f3b580.png)
I realised that this is only specific to "gaia" data since other modules of astroquery work fine. Please help me out.

**Comment by keflavich** [comment] 2021-07-31 13:01
Could you please share code snippets instead of screenshots of the code?

I tried the following and was unable to reproduce the error:
```python
from astropy import units as u, coordinates
from astroquery.gaia import Gaia
coord = coordinates.SkyCoord(280*u.deg, -60*u.deg, frame='icrs')
height = width = 0.1*u.deg
Gaia.query_object_async(coordinate=coord, width=width, height=height)
```

Given this is an SSL error, it might have been temporary - does the error persist?

**Comment by deepjyotisatpathy18032** [comment] 2021-07-31 13:10
Yes, the code mentioned by you is the code I used. I just re-run the above again and I am still getting that error. The thing is, if I use a virtual environment I get that error(only in case of gaia) but when I run the code not in a virtual environment, I don't get it.

**Comment by bsipocz** [comment] 2023-09-26 18:10
I'm closing this as we couldn't reproduce and this was very likely nothing to do with astroquery but the virtual env instead. Please update the comments if you still or again run into this.

**Closed by bsipocz** 2023-09-26 18:10 UTC
Labels: gaia
