### ISSUE TITLE
Getting bibcodelists from Simbad

### ISSUE THREAD

**Issue by jrthorstensen** [astropy/astroquery#2776] opened 2023-07-21 18:40 UTC
I expect this is a solved problem but I haven't found the answer.

I have a list of about 30 objects and would like to automatically get the SIMBAD reference lists for all of them -- basically, the output that you get in the web interface when you hit the "Display" in the "References" section of an object's main SIMBAD page, namely the bibcode, title, authors, and so on.

I can get the number of references easily enough, by adding 'bibcodelist' to the votable fields:  

 
```
from astroquery.simbad import Simbad
import astropy.units as u
from astropy.coordinates import SkyCoord

cel = SkyCoord("7 31 21.09","-10 21 50.0",unit=(u.hourangle,u.deg))
mysimbad = Simbad()
mysimbad.add_votable_fields('bibcodelist') 
result_table = mysimbad.query_region(cel, radius = 2.5 * u.arcsec)

```
This works fine, returning a table line with the number of references for the object, 30 in this case.  But I want the references spelled out, so guided by the [simbad scripting documentation](http://simbad.u-strasbg.fr/Pages/guide/sim-fscript.htx), section 4.3.11, I ran the code above but with

`mysimbad.add_votable_fields('bibcodelist(R)')`

This generated the following exception: 

```
astroquery.exceptions.TableParseError: Failed to parse SIMBAD result! The raw response can be found in self.last_response, and the error in self.last_table_parse_error. The attempted parsed result is in self.last_parsed_result.
 Exception: None:49:195: ValueError: invalid literal for int() with base 10: "1943an....274...36h\nastron. nachr., 274, 36-40 (1943)\nhoffmeister c.\n213 neue veraenderliche.\n\n1956apj...124..346c\nastrophys. j., 124, 346-366 (1956)\ncameron d. and nassau j.j.\nspectral class (in row 0, col 'BIBLIST_R')
```

suggesting that the astroquery is expecting an integer number instead of a bibliography entry.  

Suggestions, anyone?  Thanks!  -- John Thorstensen

**Comment by bsipocz** [comment] 2023-07-24 18:48
This may very well be an upstream issue, as the error is coming directly from the votable parser in astropy from L194 
(`            tbl = votable.parse_single_table(self.bytes, verify='warn')` ).

Here is the full XML string of the response:
```
'<?xml version="1.0" encoding="UTF-8"?>\n<VOTABLE xmlns="http://www.ivoa.net/xml/VOTable/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.2 http://www.ivoa.net/xml/VOTable/v1.2" version="1.2">\n<DEFINITIONS>\n<COOSYS ID="COOSYS" equinox="2000" epoch="J2000" system="ICRS"/>\n</DEFINITIONS>\n<RESOURCE name="Simbad query" type="results">\n<TABLE ID="SimbadScript" name="default"><DESCRIPTION>Simbad script executed on 2023.07.24CEST20:28:55</DESCRIPTION>\n<FIELD ID="MAIN_ID" name="MAIN_ID" datatype="char" width="22" ucd="meta.id;meta.main" arraysize="*">\n<DESCRIPTION>Main identifier for an object</DESCRIPTION>\n<LINK value="${MAIN_ID}" href="http://simbad.u-strasbg.fr/simbad/sim-id?Ident=${MAIN_ID}&amp;NbIdent=1"/>\n</FIELD>\n<FIELD ID="RA" name="RA" datatype="char" precision="8" width="13" ucd="pos.eq.ra;meta.main" arraysize="13" unit="&quot;h:m:s&quot;">\n<DESCRIPTION>Right ascension</DESCRIPTION>\n</FIELD>\n<FIELD ID="DEC" name="DEC" datatype="char" precision="8" width="13" ucd="pos.eq.dec;meta.main" arraysize="13" unit="&quot;d:m:s&quot;">\n<DESCRIPTION>Declination</DESCRIPTION>\n</FIELD>\n<FIELD ID="RA_PREC" name="RA_PREC" datatype="short" width="2">\n<DESCRIPTION>Right ascension precision</DESCRIPTION>\n</FIELD>\n<FIELD ID="DEC_PREC" name="DEC_PREC" datatype="short" width="2">\n<DESCRIPTION>Declination precision</DESCRIPTION>\n</FIELD>\n<FIELD ID="COO_ERR_MAJA" name="COO_ERR_MAJA" datatype="float" precision="3" width="6" ucd="phys.angSize.smajAxis;pos.errorEllipse;pos.eq" unit="mas">\n<DESCRIPTION>Coordinate error major axis</DESCRIPTION>\n</FIELD>\n<FIELD ID="COO_ERR_MINA" name="COO_ERR_MINA" datatype="float" precision="3" width="6" ucd="phys.angSize.sminAxis;pos.errorEllipse;pos.eq" unit="mas">\n<DESCRIPTION>Coordinate error minor axis</DESCRIPTION>\n</FIELD>\n<FIELD ID="COO_ERR_ANGLE" name="COO_ERR_ANGLE" datatype="short" width="3" ucd="pos.posAng;pos.errorEllipse;pos.eq" unit="deg">\n<DESCRIPTION>Coordinate error angle</DESCRIPTION>\n</FIELD>\n<FIELD ID="COO_QUAL" name="COO_QUAL" datatype="char" width="1" ucd="meta.code.qual;pos.eq">\n<DESCRIPTION>Coordinate quality</DESCRIPTION>\n</FIELD>\n<FIELD ID="COO_WAVELENGTH" name="COO_WAVELENGTH" datatype="char" width="1" ucd="instr.bandpass;pos.eq">\n<DESCRIPTION>Wavelength class for the origin of the coordinates (R,I,V,U,X,G)</DESCRIPTION>\n</FIELD>\n<FIELD ID="COO_BIBCODE" name="COO_BIBCODE" datatype="char" width="19" ucd="meta.bib.bibcode;pos.eq" arraysize="*">\n<DESCRIPTION>Coordinate reference</DESCRIPTION>\n</FIELD>\n<FIELD ID="BIBLIST" name="BIBLIST" datatype="int" ucd="meta.bib">\n<DESCRIPTION>List of Bibcodes</DESCRIPTION>\n<LINK value="ref (${BIBLIST})" href="http://simbad.u-strasbg.fr/simbad/sim-id?bibdisplay=refsum&amp;Ident=${MAIN_ID}#lab_bib"/>\n</FIELD>\n<FIELD ID="BIBLIST_R" name="BIBLIST_R" datatype="int" ucd="meta.bib">\n<DESCRIPTION>List of Bibcodes</DESCRIPTION>\n<LINK value="ref (${BIBLIST})" href="http://simbad.u-strasbg.fr/simbad/sim-id?bibdisplay=refsum&amp;Ident=${MAIN_ID}#lab_bib"/>\n</FIELD>\n<FIELD ID="SCRIPT_NUMBER_ID" name="SCRIPT_NUMBER_ID" datatype="int" precision="1" width="2" ucd="meta.number"/>\n<DATA>\n<TABLEDATA>\n<TR><TD>V* KQ Mon</TD><TD>07 31 21.1284198264</TD><TD>-10 21 49.397268420</TD><TD>14</TD><TD>14</TD><TD>0.0121</TD><TD>0.0135</TD><TD>90</TD><TD>A</TD><TD>Opt</TD><TD>2020yCat.1350....0G</TD><TD>30</TD><TD>1943AN....274...36H\nAstron. Nachr., 274, 36-40 (1943)\nHOFFMEISTER C.\n213 neue Veraenderliche.\n\n1956ApJ...124..346C\nAstrophys. J., 124, 346-366 (1956)\nCAMERON D. and NASSAU J.J.\nSpectral classification of red variables along the galactic equator.\n\n1957ApJ...125..195N\nAstrophys. J., 125, 195-208 (1957)\nNASSAU J.J. and BLANCO V.M.\nCarbon stars in two northern Milky Way zones.\n\n1966VeSon...7...61G\nVeroeff. Sternwarte Sonneberg, 7, 61-228 (1966)\nGESSNER H.\nDie veranderlichen Sterne der nordlichen Milchstrasse. Teil XIII.\n\n1982IUE82......460S\nAdvances in ultraviolet astronomy: Four years of IUE Research. Proc. Symp. held\nat NASA Goddard Space Flight Center, Greenbelt, Maryland, Mar.30-Apr.1, 1982,\nEd. Y. Kondo, J.M. Mead, R.D. Chapman, NASA CP-2238., 460-464 (1982)\nSION E.M. and GUINAN E.F.\nThe nova-like variable KQ Mon and the nature of the UX Ursa Majoris stars.\n\n1983MmSAI..54..467S\nMem. Soc. Astron. Ital., 54, 467-491 (1983)\nSELVELLI P.L. and HACK M.\nIUE observations of cataclysmic variables.\n\n1984A&amp;AS...56..441B\nAstron. Astrophys., Suppl. Ser., 56, 441-448 (1984)\nBRUCH A.\nA catalogue of UBV colours of cataclysmic variables.\n\n1990SSRv...52..203L\nSpace Sci. Rev., 52, 203-706 (1990)\nLA DOUS C.\nA catalogue of low-resolution IUE spectra of dwarf novae and nova-like stars\n\n1991A&amp;A...252..100L\nAstronomy and Astrophysics, volume 252, 100-122 (1991)\nLA DOUS C.\nNew insights from a statistical analysis of IUE spectra of dwarf novae and\nnova-like stars. I. Inclination effects in lines and continua.\n\n1993PASP..105..127D\nPubl. Astron. Soc. Pac., 105, 127-245 (1993)\nDOWNES R.A. and SHARA M.M.\nA catalog and atlas of cataclysmic variables.\n\n1994A&amp;AS..104...79B\nAstron. Astrophys., Suppl. Ser., 104, 79-88 (1994/April-1)\nBRUCH A. and ENGEL A.\nA catalogue of UBV colours of cataclysmic variables.\n\n1994A&amp;AS..107..503Z\nAstron. Astrophys., Suppl. Ser., 107, 503-514 (1994/November-1)\nZWITTER T. and MUNARI U.\nCCD spectrophotometry of CVs. I. 4600-9000A low resolution atlas for 31 faint\nsystems.\n\n1997A&amp;AS..124...55C\nAstron. Astrophys., Suppl. Ser., 124, 55-56 (1997/July-0)\nCIESLINSKI D., JABLONSKI F.J. and STEINER J.E.\nSouthern and equatorial irregular variables. I. Photoelectric photometry.\n\n1997PASP..109..345D\nPubl. Astron. Soc. Pac., 109, 345-440 (1997/April-0)\nDOWNES R., WEBBINK R.F. and SHARA M.M.\nA catalog and atlas of cataclysmic variables-second edition.\n\n2000IBVS.4878....1K\nIAU Inform. Bull. Var. Stars, 4878, 1-7 (2000/April-0)\nKINNUNEN T. and SKIFF B.A.\nCoordinates and identifications for Sonneberg variables on MVS 275-281.\n\n2001PASP..113..764D\nPubl. Astron. Soc. Pac., 113, 764-768 (2001/June-0)\nDOWNES R.A., WEBBINK R.F., SHARA M.M., RITTER H., KOLB U. and DUERBECK H.W.\nA catalog and atlas of cataclysmic variables: the living edition.\n\n2002ApJ...565..511H\nAstrophys. J., 565, 511-538 (2002/January-3)\nHOARD D.W., WACHTER S., CLARK L.L. and BOWERS T.P.\nInfrared properties of cataclysmic variables in the 2 micron all-sky survey\nsecond incremental data release.\n\n2003MNSSA..62...74W\nMon. Notes Astron. Soc. South Africa, 62, 74-84 (2003)\nWARNER B.\nStellar apoplexy, convalescence and recovery: the life cycles of cataclysmic\nvariable stars.\n\n2004MNSSA..63...89M\nMon. Notes Astron. Soc. South Africa, 63, 89-91 (2004)\nMONARD B.\nBronberg Observatory (CBA Pretoria) annual report for 2003.\n\n2005IBVS.5627....1S\nIAU Inform. Bull. Var. Stars, 5627, 1 (2005/May-0)\nSCHMIDTOBREICK L., TAPPERT C., GALLI L. and WHITING A.\nOn the orbital period of KQ Mon.\n\n2008NewA...13..133A\nNew Astronomy, 13, 133-143 (2008)\nAK T., BILIR S., AK S. and EKER Z.\nSpatial distribution and galactic model parameters of cataclysmic variables.\n\n2012A&amp;A...548A..79A\nAstronomy and Astrophysics, volume 548A, 79-79 (2012/12-1)\nALFONSO-GARZON J., DOMINGO A., MAS-HESSE J.M. and GIMENEZ A.\nThe first INTEGRAL-OMC catalogue of optically variable sources.\n\n2012MmSAI..83..610S\nMem. Soc. Astron. Ital., 83, 610-613 (2012)\nSCHMIDTOBREICK L., RODRIGUEZ-GIL P. and GANSICKE B.T.\nThe search for SW Sex type stars .\n\n2013AJ....145..168W\nAstron. J., 145, 168 (2013/June-0)\nWOLFE A., SION E.M. and BOND H.E.\nFar-ultraviolet spectroscopy of the nova-like variable KQ Monocerotis: a new SW\nSextantis star?\n\n2017ApJ...846...52G\nAstrophys. J., 846, 52-52 (2017/September-1)\nGODON P., SION E.M., BALMAN S. and BLAIR W.P.\nModifying the standard disk model for the Ultraviolet spectral analysis of\ndisk-dominated cataclysmic variables. I. The novalikes MV Lyrae, BZ\nCamelopardalis, and V592 Cassiopeiae.\n\n2018AJ....156..241H\nAstron. J., 156, 241-241 (2018/November-0)\nHEINZE A.N., TONRY J.L., DENNEAU L., FLEWELLING H., STALDER B., REST A.,\nSMITH K.W., SMARTT S.J. and WEILAND H.\nA first catalog of variable stars measured by the Asteroid Terrestrial-impact\nLast Alert System (ATLAS).\n\n2019A&amp;A...621A..38G\nAstronomy and Astrophysics, volume 621A, 38-38 (2019/1-1)\nGEIER S., RADDI R., GENTILE FUSILLO N.P. and MARSH T.R.\nThe population of hot subdwarf stars studied with Gaia. II. The Gaia DR2\ncatalogue of hot subluminous stars.\n\n2020MNRAS.492L..40A\nMon. Not. R. Astron. Soc., 492, L40 (2020/February-2)\nABRIL J., SCHMIDTOBREICK L., EDEROCLITE A. and LOPEZ-SANJUAN C.\nDisentangling cataclysmic variables in Gaia\'s HR diagram.\n\n2023MNRAS.520.3355S\nMon. Not. R. Astron. Soc., 520, 3355-3367 (2023/April-2)\nSTEFANOV S.Y. and STEFANOV A.K.\nTilted discs in six poorly studied cataclysmic variables.\n\n2023AJ....165..163C\nAstron. J., 165, 163 (2023/April-0)\nCANBAY R., BILIR S., OZDONMEZ A. and AK T.\nGalactic Model Parameters and Spatial Density of Cataclysmic Variables in the\nGaia Era: New Constraints on Population Models.</TD><TD>1</TD></TR>\n\n</TABLEDATA>\n\n</DATA>\n</TABLE>\n</RESOURCE>\n</VOTABLE>'
```

cc @tomdonaldson to see whether it's indeed an astropy votable issue.

**Comment by ManonMarchand** [comment] 2023-07-31 10:03
Hello all, 

It's not a parser issue but rather on our side: 

```
<FIELD ID="BIBLIST_R" name="BIBLIST_R" datatype="int" ucd="meta.bib">
<DESCRIPTION>List of Bibcodes</DESCRIPTION>
```

@aoberto : should this field be of `datatype="char"` ?

Thanks for spotting the issue!

**Comment by bsipocz** [comment] 2023-07-31 18:33
thanks @ManonMarchand!

**Comment by aoberto** [comment] 2023-08-02 08:59
Yes @ManonMarchand Simbad should change the datatype of this field, I am looking into it

**Comment by aoberto** [comment] 2023-08-10 08:19
This should be fixed in Simbad, please, can you confirm ? (remember to clean you cache)

**Comment by bsipocz** [comment] 2023-08-11 16:51
Thanks @aoberto for the fix. The example indeed works for me now while I could reproduce the original issue.

**Closed by bsipocz** 2023-08-11 16:51 UTC
Labels: bug, Upstream, simbad
