### ISSUE TITLE
SDSS.query_region example fails

### ISSUE THREAD

**Issue by banados** [astropy/astroquery#475] opened 2015-01-21 21:06 UTC
When I try to run the example in: http://astroquery.readthedocs.org/en/latest/sdss/sdss.html#module-astroquery.sdss

```
from astroquery.sdss import SDSS
from astropy import coordinates as coords
pos = coords.SkyCoord('0h8m05.63s +14d50m23.3s', frame='icrs')
xid = SDSS.query_region(pos, spectro=True)
```

I get the following error:

ERROR: OverflowError: Python int too large to convert to C long [numpy.lib.npyio]

Does anyone know what is the problem here? astroquery, numpy?

Thanks

python 2.7.3

astropy.**version**
'0.4.3'

astroquery.**version**
 '0.3.dev'

np.**version**
'1.9.1'

requests.**version**
'2.5.1'

**Comment by keflavich** [comment] 2015-01-22 06:43
Is it possible that you're on a 32-bit system?  Check this:

```
In [6]: import sys

In [7]: sys.maxint
Out[7]: 9223372036854775807
```
If you have 2147483648 (2**31) instead of that larger number, that indicates you are on a 32 bit system, which may be the cause of the error.  Nonetheless, this shouldn't be system dependent.   The error is coming from `numpy.genfromtext`, so I think we should ask this question on a numpy mailing list.

**Comment by banados** [comment] 2015-01-22 09:16
That is exactly the case:

    In [1]: import sys
    In [2]: sys.maxint
    Out[2]: 2147483647

what is the exact question for the numpy folks then?

Should it be a warning in the meantime saying that sdss.query_region currently does not work on a 32-bit system?

**Comment by keflavich** [comment] 2015-01-22 13:20
I am not entirely sure.  We should research the problem a little further first - I think it may be possible to replace `numpy.genfromtext` with `astropy.table.read` or perhaps send appropriate kwargs to `genfromtext` to avoid this error

**Comment by astrofrog** [comment] 2015-03-05 12:20
I've opened a Numpy issue: https://github.com/numpy/numpy/issues/5635

**Comment by astrofrog** [comment] 2015-03-06 18:55
@banados @keflavich - just for the record I have opened a PR to Numpy and this should be fixed in Numpy 1.10 hopefully: https://github.com/numpy/numpy/pull/5635.

As a side note though, is there a reason not to use ``io.ascii`` here?

**Comment by astrofrog** [comment] 2015-03-06 20:42
@banados - try updating to the latest developer version of Numpy, since my pull request (https://github.com/numpy/numpy/pull/5635) has now been merged.

**Comment by keflavich** [comment] 2015-03-06 20:45
@astrofrog - no, I don't think there is, just need a PR to do it...

**Comment by astrofrog** [comment] 2015-03-06 20:56
Ok, but in the mean time this will be fixed in Numpy 1.10 and is fixed in Numpy dev, so maybe not high priority.

**Comment by bsipocz** [comment] 2015-04-21 08:38
@astrofrog - do we know when numpy 1.10 is out?

**Comment by bsipocz** [comment] 2017-03-04 22:04
I'm closing this as the upstream fix has been merged into numpy quite a long time ago. Please do reopen if you still see it.

**Closed by bsipocz** 2017-03-04 22:04 UTC
Labels: sdss
