### ISSUE TITLE
html5lib import error (in skyview module)

### ISSUE THREAD

**Issue by bwinkel** [astropy/astroquery#914] opened 2017-05-12 15:05 UTC
Just installed astroquery. If I do
```py3bt
from astroquery.skyview import SkyView
```
I get
```bash
AttributeError                            Traceback (most recent call last)
<ipython-input-5-dd03a5453ece> in <module>()
----> 1 from astroquery.skyview import SkyView

/home/bwinkel/local/anaconda3/lib/python3.5/site-packages/astroquery/skyview/__init__.py in <module>()
     14 conf = Conf()
     15 
---> 16 from .core import SkyView, SkyViewClass
     17 
     18 __all__ = ['SkyView', 'SkyViewClass',

/home/bwinkel/local/anaconda3/lib/python3.5/site-packages/astroquery/skyview/core.py in <module>()
      1 # Licensed under a 3-clause BSD style license - see LICENSE.rst
      2 import pprint
----> 3 from bs4 import BeautifulSoup
      4 from astropy.extern.six.moves.urllib import parse as urlparse
      5 from astropy.extern import six

/home/bwinkel/local/anaconda3/lib/python3.5/site-packages/bs4/__init__.py in <module>()
     28 import warnings
     29 
---> 30 from .builder import builder_registry, ParserRejectedMarkup
     31 from .dammit import UnicodeDammit
     32 from .element import (

/home/bwinkel/local/anaconda3/lib/python3.5/site-packages/bs4/builder/__init__.py in <module>()
    312 register_treebuilders_from(_htmlparser)
    313 try:
--> 314     from . import _html5lib
    315     register_treebuilders_from(_html5lib)
    316 except ImportError:

/home/bwinkel/local/anaconda3/lib/python3.5/site-packages/bs4/builder/_html5lib.py in <module>()
     68 
     69 
---> 70 class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
     71 
     72     def __init__(self, soup, namespaceHTMLElements):

AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```

I have
```python
astroquery.__version__ == '0.3.5'
html5lib.__version__ == '0.999999999'
```

**Comment by AyushYadav** [comment] 2017-05-22 09:21
@bwinkel I am able to reproduce the same error. Let me look it over once. This seems as internal library issue.

**Comment by AyushYadav** [comment] 2017-05-23 12:58
@bwinkel In the dev version of astroquery this error is not occuring maybe because of the changes in the form we import the library. So with the `0.3.6` version you won't see this issue. I have run the import statements above in the developer version of the current code and this error does not occur. If you wish to use the developer version of astroquery, you can refer to the link here, [Developers Guide](http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html?highlight=%22setup.py%20develop%22#activate-the-development-version-of-astropy).

**Comment by bwinkel** [comment] 2017-05-24 10:55
Still get the same error if I install from source (`astroquery.__version__ == '0.3.6.dev3941'`).

**Comment by AyushYadav** [comment] 2017-05-24 11:19
@bwinkel I tried this in my dev version
`astroquery.__version__ == 0.3.6.dev394`1`
`html5lib.__version__ == 0.999999999`

I just checked it out again, I am not having this error with these configs. Maybe it is a issue with your `PATH` or maybe you can try to uninstall the `html5lib` package and re-install it. Because I am not able to see this error in my bleeding edge dev installation. Let us know if you find something in this.

**Comment by bwinkel** [comment] 2017-05-24 11:54
Tried, but unfortunately it doesn't help. Working on anaconda (python 3). Will try on another machine later.

**Comment by keflavich** [comment] 2017-05-24 13:59
Perhaps try removing and reinstalling BeautifulSoup, since that's where the failure actually happened?

**Comment by bwinkel** [comment] 2017-05-24 21:23
> Perhaps try removing and reinstalling BeautifulSoup, since that's where the failure actually happened?

Good hint. Works now. I had bs version 4.4.1 and upgraded to 4.6. Perhaps, you could change the requirements accordingly, so that pip automatically updates the package?

**Comment by keflavich** [comment] 2017-05-24 21:30
I suspect it wasn't a version issue, but somehow a corrupted library issue, based on your original error report.

**Comment by bwinkel** [comment] 2017-05-29 11:28
I tried re-installing BS4 4.4.1 and again it crashes. Starting with 4.5 it works for me. I also tried it on another computer and apparently version 4.4.1 works there. So, I have no idea what's going on. 

Anyway, thanks a lot for your help!

**Comment by keflavich** [comment] 2017-05-29 15:29
Thanks for the information @bwinkel.  For now, I think we're best off closing this issue and leaving it up as information in case another user encounters a similar issue.  Since the BS4 behavior is different on different machines, though, I don't think there's anything we should do in terms of version dependencies just yet.

**Closed by keflavich** 2017-05-29 15:29 UTC
Labels: question
