### ISSUE TITLE
pip install fails with `has different version in metadata: '0.4.2.dev0'`

### ISSUE THREAD

**Issue by hamogu** [astropy/astroquery#2042] opened 2021-04-17 14:31 UTC
Pip install (in this case into a conda environment that did not have astroquery before) fails with
```
(ciao) [Hanss-MacBook-Air:~/projects/Chandraprojects/HotestCoolStar] hamogu% pip install --pre astroquery
Collecting astroquery
  Downloading astroquery-0.4.2.dev6449.tar.gz (4.6 MB)
     |████████████████████████████████| 4.6 MB 2.9 MB/s 
ERROR: Requested astroquery from https://files.pythonhosted.org/packages/65/41/3cc633331a276f78aa5fa110c7dc71e146dd7d14346f3460534a264e0a5d/astroquery-0.4.2.dev6449.tar.gz#sha256=df7786a5ba87c966f705f6fce02d73bd7c48a748d7e0a89f0531bcd544a7a074 has different version in metadata: '0.4.2.dev0'
```

Probably depends on the pip version:
```
(ciao) [Hanss-MacBook-Air:~/projects/Chandraprojects/HotestCoolStar] hamogu% pip --version
pip 20.3.3 from /Users/hamogu/anaconda3/envs/ciao/lib/python3.7/site-packages/pip (python 3.7)
```

I've been able to work around it by doing
```
pip install --pre astroquery --use-deprecated=legacy-resolver
```
following the advice here: https://github.com/pypa/pip/issues/9203

**Comment by bsipocz** [comment] 2021-04-17 23:47
Yes we're aware of the issue and indeed your workaround is the currently known thing, or to downgrade pip.

Closing this a duplicate of #1986

**Closed by bsipocz** 2021-04-17 23:47 UTC
