### ISSUE TITLE
Comparisons broken by new versions of Astropy

### ISSUE THREAD

**Issue by odysseus9672** [astropy/astroquery#2771] opened 2023-07-13 20:59 UTC
The following comparisons in [`astroquery/astroquery/skyview/core.py`](https://github.com/astropy/astroquery/blob/main/astroquery/skyview/core.py) are broken by updates to how comparisons with quantities are handled by astropy:
```
        elif width and height:
            size_deg = "{0},{1}".format(width.to(u.deg).value,
                                        height.to(u.deg).value)
        elif width and height:
            raise ValueError("Must specify width and height if you "
                             "specify either.")
```

The second comparison is also bugged – it's identical to the one above, so it will never trigger. It should be an `or`. I would suggest modifying the code to read
```
        elif width is not None and height is not None:
            size_deg = "{0},{1}".format(width.to(u.deg).value,
                                        height.to(u.deg).value)
        elif width is not None or height is not None:
            raise ValueError("Must specify width and height if you "
                             "specify either.")
```

**Comment by bsipocz** [comment] 2023-07-25 23:55
Closing as a duplicate of https://github.com/astropy/astroquery/issues/2756

**Closed by bsipocz** 2023-07-25 23:55 UTC
