### ISSUE TITLE
I am getting this error 

### ISSUE THREAD

**Issue by Dr-Aranya-S** [astropy/astroquery#2476] opened 2022-07-29 09:50 UTC
code
```
tables = Gaia.load_tables(only_names=True)
for table in (tables):
    print (table.get_qualified_name())
```
error
INFO: Retrieving tables... [astroquery.utils.tap.core]
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
Input In [14], in <cell line: 1>()
----> 1 tables = Gaia.load_tables(only_names=True)
      2 for table in (tables):
      3     print (table.get_qualified_name())

File /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/utils/tap/core.py:805, in TapPlus.load_tables(self, only_names, include_shared_tables, verbose).......

**Comment by bsipocz** [comment] 2022-11-18 17:56
This example works for me, so I'm closing. If you still see the issue with the latest astroquery version, please provide some more details that helps us reproduce.


```
In [8]: tables = Gaia.load_tables(only_names=True)
   ...: for table in (tables):
   ...:     print (table.get_qualified_name())
   ...: 
INFO: Retrieving tables... [astroquery.utils.tap.core]
INFO: Parsing tables... [astroquery.utils.tap.core]
INFO: Done. [astroquery.utils.tap.core]
external.external.apassdr9
external.external.gaiadr2_astrophysical_parameters
external.external.gaiadr2_geometric_distance
external.external.gaiaedr3_distance
external.external.gaiaedr3_gcns_main_1
external.external.gaiaedr3_gcns_rejected_1
external.external.gaiaedr3_spurious
external.external.galex_ais
external.external.ravedr5_com
external.external.ravedr5_dr5
external.external.ravedr5_gra
external.external.ravedr5_on
external.external.ravedr6
external.external.sdssdr13_photoprimary
external.external.skymapperdr1_master
external.external.skymapperdr2_master
external.external.tmass_xsc
gaiadr1.gaiadr1.aux_qso_icrf2_match
gaiadr1.gaiadr1.ext_phot_zero_point
gaiadr1.gaiadr1.allwise_best_neighbour
gaiadr1.gaiadr1.allwise_neighbourhood
gaiadr1.gaiadr1.gsc23_best_neighbour
gaiadr1.gaiadr1.gsc23_neighbourhood
gaiadr1.gaiadr1.ppmxl_best_neighbour
gaiadr1.gaiadr1.ppmxl_neighbourhood
gaiadr1.gaiadr1.sdss_dr9_best_neighbour
gaiadr1.gaiadr1.sdss_dr9_neighbourhood
gaiadr1.gaiadr1.tmass_best_neighbour
gaiadr1.gaiadr1.tmass_neighbourhood
gaiadr1.gaiadr1.ucac4_best_neighbour
gaiadr1.gaiadr1.ucac4_neighbourhood
gaiadr1.gaiadr1.urat1_best_neighbour
gaiadr1.gaiadr1.urat1_neighbourhood
gaiadr1.gaiadr1.cepheid
gaiadr1.gaiadr1.phot_variable_time_series_gfov
gaiadr1.gaiadr1.phot_variable_time_series_gfov_statistical_parameters
gaiadr1.gaiadr1.rrlyrae
gaiadr1.gaiadr1.variable_summary
gaiadr1.gaiadr1.allwise_original_valid
gaiadr1.gaiadr1.gsc23_original_valid
gaiadr1.gaiadr1.ppmxl_original_valid
gaiadr1.gaiadr1.sdssdr9_original_valid
gaiadr1.gaiadr1.tmass_original_valid
gaiadr1.gaiadr1.ucac4_original_valid
gaiadr1.gaiadr1.urat1_original_valid
gaiadr1.gaiadr1.gaia_source
gaiadr1.gaiadr1.tgas_source
gaiadr2.gaiadr2.aux_allwise_agn_gdr2_cross_id
gaiadr2.gaiadr2.aux_iers_gdr2_cross_id
gaiadr2.gaiadr2.aux_sso_orbit_residuals
gaiadr2.gaiadr2.aux_sso_orbits
gaiadr2.gaiadr2.dr1_neighbourhood
gaiadr2.gaiadr2.allwise_best_neighbour
gaiadr2.gaiadr2.allwise_neighbourhood
gaiadr2.gaiadr2.apassdr9_best_neighbour
gaiadr2.gaiadr2.apassdr9_neighbourhood
gaiadr2.gaiadr2.gsc23_best_neighbour
gaiadr2.gaiadr2.gsc23_neighbourhood
gaiadr2.gaiadr2.hipparcos2_best_neighbour
gaiadr2.gaiadr2.hipparcos2_neighbourhood
gaiadr2.gaiadr2.panstarrs1_best_neighbour
gaiadr2.gaiadr2.panstarrs1_neighbourhood
gaiadr2.gaiadr2.ppmxl_best_neighbour
gaiadr2.gaiadr2.ppmxl_neighbourhood
gaiadr2.gaiadr2.ravedr5_best_neighbour
gaiadr2.gaiadr2.ravedr5_neighbourhood
gaiadr2.gaiadr2.sdssdr9_best_neighbour
gaiadr2.gaiadr2.sdssdr9_neighbourhood
gaiadr2.gaiadr2.tmass_best_neighbour
gaiadr2.gaiadr2.tmass_neighbourhood
gaiadr2.gaiadr2.tycho2_best_neighbour
gaiadr2.gaiadr2.tycho2_neighbourhood
gaiadr2.gaiadr2.urat1_best_neighbour
gaiadr2.gaiadr2.urat1_neighbourhood
gaiadr2.gaiadr2.sso_observation
gaiadr2.gaiadr2.sso_source
gaiadr2.gaiadr2.vari_cepheid
gaiadr2.gaiadr2.vari_classifier_class_definition
gaiadr2.gaiadr2.vari_classifier_definition
gaiadr2.gaiadr2.vari_classifier_result
gaiadr2.gaiadr2.vari_long_period_variable
gaiadr2.gaiadr2.vari_rotation_modulation
gaiadr2.gaiadr2.vari_rrlyrae
gaiadr2.gaiadr2.vari_short_timescale
gaiadr2.gaiadr2.vari_time_series_statistics
gaiadr2.gaiadr2.panstarrs1_original_valid
gaiadr2.gaiadr2.gaia_source
gaiadr2.gaiadr2.ruwe
gaiadr3.gaiadr3.gaia_source
gaiadr3.gaiadr3.gaia_source_lite
gaiadr3.gaiadr3.astrophysical_parameters
gaiadr3.gaiadr3.astrophysical_parameters_supp
gaiadr3.gaiadr3.oa_neuron_information
gaiadr3.gaiadr3.oa_neuron_xp_spectra
gaiadr3.gaiadr3.total_galactic_extinction_map
gaiadr3.gaiadr3.total_galactic_extinction_map_opt
gaiadr3.gaiadr3.commanded_scan_law
gaiadr3.gaiadr3.allwise_best_neighbour
gaiadr3.gaiadr3.allwise_neighbourhood
gaiadr3.gaiadr3.apassdr9_best_neighbour
gaiadr3.gaiadr3.apassdr9_join
gaiadr3.gaiadr3.apassdr9_neighbourhood
gaiadr3.gaiadr3.dr2_neighbourhood
gaiadr3.gaiadr3.gsc23_best_neighbour
gaiadr3.gaiadr3.gsc23_join
gaiadr3.gaiadr3.gsc23_neighbourhood
gaiadr3.gaiadr3.hipparcos2_best_neighbour
gaiadr3.gaiadr3.hipparcos2_neighbourhood
gaiadr3.gaiadr3.panstarrs1_best_neighbour
gaiadr3.gaiadr3.panstarrs1_join
gaiadr3.gaiadr3.panstarrs1_neighbourhood
gaiadr3.gaiadr3.ravedr5_best_neighbour
gaiadr3.gaiadr3.ravedr5_join
gaiadr3.gaiadr3.ravedr5_neighbourhood
gaiadr3.gaiadr3.ravedr6_best_neighbour
gaiadr3.gaiadr3.ravedr6_join
gaiadr3.gaiadr3.ravedr6_neighbourhood
gaiadr3.gaiadr3.sdssdr13_best_neighbour
gaiadr3.gaiadr3.sdssdr13_join
gaiadr3.gaiadr3.sdssdr13_neighbourhood
gaiadr3.gaiadr3.skymapperdr2_best_neighbour
gaiadr3.gaiadr3.skymapperdr2_join
gaiadr3.gaiadr3.skymapperdr2_neighbourhood
gaiadr3.gaiadr3.tmass_psc_xsc_best_neighbour
gaiadr3.gaiadr3.tmass_psc_xsc_join
gaiadr3.gaiadr3.tmass_psc_xsc_neighbourhood
gaiadr3.gaiadr3.tycho2tdsc_merge_best_neighbour
gaiadr3.gaiadr3.tycho2tdsc_merge_neighbourhood
gaiadr3.gaiadr3.urat1_best_neighbour
gaiadr3.gaiadr3.urat1_neighbourhood
gaiadr3.gaiadr3.galaxy_candidates
gaiadr3.gaiadr3.galaxy_catalogue_name
gaiadr3.gaiadr3.qso_candidates
gaiadr3.gaiadr3.qso_catalogue_name
gaiadr3.gaiadr3.nss_acceleration_astro
gaiadr3.gaiadr3.nss_non_linear_spectro
gaiadr3.gaiadr3.nss_two_body_orbit
gaiadr3.gaiadr3.nss_vim_fl
gaiadr3.gaiadr3.binary_masses
gaiadr3.gaiadr3.gold_sample_carbon_stars
gaiadr3.gaiadr3.gold_sample_fgkm_stars
gaiadr3.gaiadr3.gold_sample_oba_stars
gaiadr3.gaiadr3.gold_sample_solar_analogues
gaiadr3.gaiadr3.gold_sample_spss
gaiadr3.gaiadr3.gold_sample_ucd
gaiadr3.gaiadr3.sso_orbits
gaiadr3.gaiadr3.synthetic_photometry_gspc
gaiadr3.gaiadr3.agn_cross_id
gaiadr3.gaiadr3.frame_rotator_source
gaiadr3.gaiadr3.gaia_crf3_xm
gaiadr3.gaiadr3.alerts_mixedin_sourceids
gaiadr3.gaiadr3.science_alerts
gaiadr3.gaiadr3.gaia_source_simulation
gaiadr3.gaiadr3.gaia_universe_model
gaiadr3.gaiadr3.sso_observation
gaiadr3.gaiadr3.sso_reflectance_spectrum
gaiadr3.gaiadr3.sso_source
gaiadr3.gaiadr3.xp_summary
gaiadr3.gaiadr3.vari_agn
gaiadr3.gaiadr3.vari_cepheid
gaiadr3.gaiadr3.vari_classifier_class_definition
gaiadr3.gaiadr3.vari_classifier_definition
gaiadr3.gaiadr3.vari_classifier_result
gaiadr3.gaiadr3.vari_compact_companion
gaiadr3.gaiadr3.vari_eclipsing_binary
gaiadr3.gaiadr3.vari_epoch_radial_velocity
gaiadr3.gaiadr3.vari_long_period_variable
gaiadr3.gaiadr3.vari_microlensing
gaiadr3.gaiadr3.vari_ms_oscillator
gaiadr3.gaiadr3.vari_planetary_transit
gaiadr3.gaiadr3.vari_rad_vel_statistics
gaiadr3.gaiadr3.vari_rotation_modulation
gaiadr3.gaiadr3.vari_rrlyrae
gaiadr3.gaiadr3.vari_short_timescale
gaiadr3.gaiadr3.vari_summary
gaiadr3.gaiadr3.tycho2tdsc_merge
gaiaedr3.gaiaedr3.gaia_source
gaiaedr3.gaiaedr3.agn_cross_id
gaiaedr3.gaiaedr3.commanded_scan_law
gaiaedr3.gaiaedr3.dr2_neighbourhood
gaiaedr3.gaiaedr3.frame_rotator_source
gaiaedr3.gaiaedr3.allwise_best_neighbour
gaiaedr3.gaiaedr3.allwise_neighbourhood
gaiaedr3.gaiaedr3.apassdr9_best_neighbour
gaiaedr3.gaiaedr3.apassdr9_join
gaiaedr3.gaiaedr3.apassdr9_neighbourhood
gaiaedr3.gaiaedr3.gsc23_best_neighbour
gaiaedr3.gaiaedr3.gsc23_join
gaiaedr3.gaiaedr3.gsc23_neighbourhood
gaiaedr3.gaiaedr3.hipparcos2_best_neighbour
gaiaedr3.gaiaedr3.hipparcos2_neighbourhood
gaiaedr3.gaiaedr3.panstarrs1_best_neighbour
gaiaedr3.gaiaedr3.panstarrs1_join
gaiaedr3.gaiaedr3.panstarrs1_neighbourhood
gaiaedr3.gaiaedr3.ravedr5_best_neighbour
gaiaedr3.gaiaedr3.ravedr5_join
gaiaedr3.gaiaedr3.ravedr5_neighbourhood
gaiaedr3.gaiaedr3.sdssdr13_best_neighbour
gaiaedr3.gaiaedr3.sdssdr13_join
gaiaedr3.gaiaedr3.sdssdr13_neighbourhood
gaiaedr3.gaiaedr3.skymapperdr2_best_neighbour
gaiaedr3.gaiaedr3.skymapperdr2_join
gaiaedr3.gaiaedr3.skymapperdr2_neighbourhood
gaiaedr3.gaiaedr3.tmass_psc_xsc_best_neighbour
gaiaedr3.gaiaedr3.tmass_psc_xsc_join
gaiaedr3.gaiaedr3.tmass_psc_xsc_neighbourhood
gaiaedr3.gaiaedr3.tycho2tdsc_merge_best_neighbour
gaiaedr3.gaiaedr3.tycho2tdsc_merge_neighbourhood
gaiaedr3.gaiaedr3.urat1_best_neighbour
gaiaedr3.gaiaedr3.urat1_neighbourhood
gaiaedr3.gaiaedr3.gaia_source_simulation
gaiaedr3.gaiaedr3.gaia_universe_model
gaiaedr3.gaiaedr3.tycho2tdsc_merge
public.public.hipparcos
public.public.hipparcos_newreduction
public.public.hubble_sc
public.public.igsl_source
public.public.igsl_source_catalog_ids
public.public.tycho2
public.public.dual
tap_config.tap_config.coord_sys
tap_config.tap_config.properties
tap_schema.tap_schema.columns
tap_schema.tap_schema.key_columns
tap_schema.tap_schema.keys
tap_schema.tap_schema.schemas
tap_schema.tap_schema.tables
```

**Closed by bsipocz** 2022-11-18 17:56 UTC
