### ISSUE TITLE
votable pprint fails with "no attribute _element_name"

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#610] opened 2015-11-06 13:47 UTC
An example failure when parsing Vizier votables:

```
In [1]: from astroquery.vizier import Vizier

In [2]: rslt = Vizier.find_catalogs('Urquhart 2014')

In [3]: rslt
Out[3]: Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/IPython/core/formatters.py", line 697, in __call__
    printer.pretty(obj)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/IPython/lib/pretty.py", line 368, in pretty
    return self.type_pprinters[cls](obj, self, cycle)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/IPython/lib/pretty.py", line 623, in inner
    p.pretty(obj[key])
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/IPython/lib/pretty.py", line 383, in pretty
    return _default_pprint(obj, self, cycle)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/IPython/lib/pretty.py", line 503, in _default_pprint
    _repr_pprint(obj, p, cycle)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/IPython/lib/pretty.py", line 685, in _repr_pprint
    output = repr(obj)
  File "/Users/adam/repos/astropy/astropy/io/votable/tree.py", line 3019, in __repr__
    self._element_name,
AttributeError: 'Resource' object has no attribute '_element_name'
```

the `rslt` object is valid:

```
In [9]: type(next (iter (rslt.values())))
Out[9]: astropy.io.votable.tree.Resource
```

but it's very difficult to explore since every attempt to repr results in a traceback.  This is probably an astropy issue.

**Comment by bdilday** [comment] 2016-01-29 19:05
The example here shows no meaningful output, just a reference to the Resource objects in the dictionary. 
https://astroquery.readthedocs.org/en/latest/vizier/vizier.html

Is that the output that is desired?

I have a fix that causes a print out of the table, but now I'm not sure what the intended behavior is?

**Comment by bdilday** [comment] 2016-01-29 20:48
I've got a fix here
https://github.com/bdilday/astropy/tree/Resource_repr

and a pull request pending
https://github.com/astropy/astropy/pull/4546

**Comment by keflavich** [comment] 2016-01-29 20:56
Thanks @bdilday, that's great!  Does it solve this issue?

**Comment by bdilday** [comment] 2016-01-29 20:59
for me, yes.

**Comment by evertrol** [comment] 2016-02-03 03:08
I ran into the same problem recently.
The fix works for me.
 
But I'm not sure if printing the full XML is the best solution. In particular when multiple tables are returned (which, at a guess, should become a TableList), this can result in a quite lengthy output.

I personally don't mind the symbolic output as given in the documentation linked above. If a user likes to get the full output, it's simple a matter of calling `to_xml()` on each `Resource` individually.

Looking at the history of the `__repr__` method, it looks like things went wrong at [astropy PR 3639](https://github.com/astropy/astropy/pull/3639). 
In fact, the current `__repr__` tries not only to access a non-existent  `_element_name`, but also uses the local variable `w`, which doesn't exist (unless it's some badly named global variable).

I'll see if the astropy likes to revert to the default `__repr__` (using the standard Python symbolic output), or find a another (shorter?) implementation.

**Comment by bsipocz** [comment] 2016-11-20 16:05
I'm not sure which PR in astropy solved this (not the one referred above), but the example is definitely working with the latest master, so I'm closing this issue.

**Closed by bsipocz** 2016-11-20 16:05 UTC
Labels: bug, vizier

**Comment by bsipocz** [comment] 2016-11-20 16:08
The PR was probably https://github.com/astropy/astropy/pull/5382
