### ISSUE TITLE
Fermi: Not working?

### ISSUE THREAD

**Issue by sbest49** [astropy/astroquery#1211] opened 2018-07-19 20:46 UTC

**Comment by keflavich** [comment] 2018-07-27 15:59
We need more details to help.  At least give an example of a failed query.

**Comment by sbest49** [comment] 2018-07-27 18:16
The page the request returns is just the same but with the fields filled in. I think that's why it doesn't find the result url.
This is the result I get:

/usr/local/lib/python3.5/dist-packages/astroquery/fermi/__init__.py:37: UserWarning: Experimental: Fermi-LAT has not yet been refactored to have its API match the rest of astroquery.
  warnings.warn("Experimental: Fermi-LAT has not yet been refactored to have "
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    result = fermi.FermiLAT.query_object('M31', energyrange_MeV='1000, 100000', obsdates='2013-01-01 00:00:00, 2013-01-02 00:00:00')
  File "/usr/local/lib/python3.5/dist-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/astroquery/fermi/core.py", line 49, in query_object_async
    raise ValueError("Results did not contain a result url. something "
ValueError: Results did not contain a result url. something went awry (that hasn't been tested yet)

**Comment by keflavich** [comment] 2018-09-19 00:03
Right, sorry we haven't answered this.  It looks like a simple failure in the regular expression being used; we need a more flexible one?  The results look like:
```
The results of your query may be found at <a href="https://fermi.gsfc.nasa.gov/cgi-bin/ssc/LAT/QueryResults.cgi?id=L1809182001077FA3883F37">https://fermi.gsfc.nasa.gov/cgi-bin/ssc/LAT/QueryResults.cgi?id=L1809182001077FA3883F37</a>.</p></div></div>
```

and the `re` is:
```
re.compile('The results of your query may be found at <a href="(http://fermi.gsfc.nasa.gov/.*?)"')
```

Ah, this is trivial, we need to use https.

**Comment by DavidIsrayelyan** [comment] 2021-07-02 18:08
@keflavich  Good evening. 
Now I have the same problem. But the version is the newest one. Is there any idea from which it may happen?

**Comment by bsipocz** [comment] 2021-07-02 18:27
The query above works for me:

```
In [10]: result = fermi.FermiLAT.query_object('M31', energyrange_MeV='1000, 100000', obsdates='2013-01-01 00:00:00, 2013-01-02 00:00:00')

In [11]: result
Out[11]: 
['https://fermi.gsfc.nasa.gov/FTP/fermi/data/lat/queries/L2107021419605192CEB685_PH00.fits',
 'https://fermi.gsfc.nasa.gov/FTP/fermi/data/lat/queries/L2107021419605192CEB685_SC00.fits']
```

You could maybe try to clean up the cache (normally located at ~/.astropy/cache/astroquery). If you still see the issue, please post a failing example with full tracelog.

**Comment by DavidIsrayelyan** [comment] 2021-07-13 10:17
![Screenshot from 2021-07-13 14-15-48](https://user-images.githubusercontent.com/22592990/125435141-3c91ebe1-2ef3-40af-b353-1a38f1f96ba1.png)
Here is an example of an error.

**Comment by bsipocz** [comment] 2022-11-27 05:46
I'm going ahead and close this. If anyone runs into this problem again, please provide a reproducible example of the failure.

**Closed by bsipocz** 2022-11-27 05:46 UTC
Labels: close?, fermi
