### ISSUE TITLE
heasarc.query_region crashes when there are no observations near the region in HEASARC

### ISSUE THREAD

**Issue by noelklingler** [astropy/astroquery#2739] opened 2023-05-19 00:43 UTC
I'm trying to search HEASARC for Swift observations at an input RA, Dec.  I'm following the basic method/syntax as stated on https://astroquery.readthedocs.io/en/latest/heasarc/heasarc.html 
It works fine when I'm searching around a region for which observations exist.  But if I search around an RA, Dec unobserved by Swift, the entire code crashes with **MANY** errors (pasted at the end), instead of simply returning something like "no results found".

`from astroquery.heasarc import Heasarc`
`from astropy.coordinates import SkyCoord`
`import numpy`

`coords = SkyCoord(275.00, 44.00, unit='deg', frame='icrs')`
`heasarc.query_region(coords, mission='swiftuvlog', radius='7 arcmin', fields='All')`

However, if I simply change the coordinates to something that has definitely be observed (e.g., AT2017gfo, at RA, Dec = 197.4503, -23.3814), the code works perfectly.

This needs to be fixed.  The code shouldn't crash, it should just return an empty table, or print "no results found", or something.  Can someone please fix this?  Thanks

---

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/opt/anaconda3/lib/python3.9/site-packages/astroquery/heasarc/core.py:242, in HeasarcClass._parse_result(self, response, verbose)
    241 data = BytesIO(response.content)
--> 242 table = Table.read(data, hdu=1)
    243 return table

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/table/connect.py:62, in TableRead.__call__(self, *args, **kwargs)
     60 descriptions = kwargs.pop('descriptions', None)
---> 62 out = self.registry.read(cls, *args, **kwargs)
     64 # For some readers (e.g., ascii.ecsv), the returned `out` class is not
     65 # guaranteed to be the same as the desired output `cls`.  If so,
     66 # try coercing to desired class without copying (io.registry.read
     67 # would normally do a copy).  The normal case here is swapping
     68 # Table <=> QTable.

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/registry/core.py:212, in UnifiedInputRegistry.read(self, cls, format, cache, *args, **kwargs)
    211 reader = self.get_reader(format, cls)
--> 212 data = reader(*args, **kwargs)
    214 if not isinstance(data, cls):
    215     # User has read with a subclass where only the parent class is
    216     # registered.  This returns the parent class, so try coercing
    217     # to desired subclass.

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/connect.py:234, in read_table_fits(input, hdu, astropy_native, memmap, character_as_bytes, unit_parse_strict, mask_invalid)
    233 try:
--> 234     return read_table_fits(
    235         hdulist, hdu=hdu,
    236         astropy_native=astropy_native,
    237         unit_parse_strict=unit_parse_strict,
    238         mask_invalid=mask_invalid,
    239     )
    240 finally:

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/connect.py:217, in read_table_fits(input, hdu, astropy_native, memmap, character_as_bytes, unit_parse_strict, mask_invalid)
    216     else:
--> 217         raise ValueError("No table found")
    219 elif isinstance(input, (TableHDU, BinTableHDU, GroupsHDU)):

ValueError: No table found

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File ~/opt/anaconda3/lib/python3.9/site-packages/astroquery/heasarc/core.py:246, in HeasarcClass._parse_result(self, response, verbose)
    245 try:
--> 246     return self._fallback(response.text)
    247 except Exception as e:

File ~/opt/anaconda3/lib/python3.9/site-packages/astroquery/heasarc/core.py:200, in HeasarcClass._fallback(self, text)
    199 data = StringIO(text)
--> 200 header = fits.getheader(data, 1)  # Get header for column info
    201 colstart = [y for x, y in header.items() if "TBCOL" in x]

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/convenience.py:103, in getheader(filename, *args, **kwargs)
    102 mode, closed = _get_file_mode(filename)
--> 103 hdulist, extidx = _getext(filename, mode, *args, **kwargs)
    104 try:

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/convenience.py:1071, in _getext(filename, mode, ext, extname, extver, *args, **kwargs)
   1069     raise TypeError('extver alone cannot specify an extension.')
-> 1071 hdulist = fitsopen(filename, mode=mode, **kwargs)
   1073 return hdulist, ext

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py:175, in fitsopen(name, mode, memmap, save_backup, cache, lazy_load_hdus, ignore_missing_simple, **kwargs)
    173     raise ValueError(f'Empty filename: {name!r}')
--> 175 return HDUList.fromfile(name, mode, memmap, save_backup, cache,
    176                         lazy_load_hdus, ignore_missing_simple, **kwargs)

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py:410, in HDUList.fromfile(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, ignore_missing_simple, **kwargs)
    402 """
    403 Creates an `HDUList` instance from a file-like object.
    404 
   (...)
    407 documentation for details of the parameters accepted by this method).
    408 """
--> 410 return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
    411                      save_backup=save_backup, cache=cache,
    412                      ignore_missing_simple=ignore_missing_simple,
    413                      lazy_load_hdus=lazy_load_hdus, **kwargs)

File ~/opt/anaconda3/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py:1090, in HDUList._readfrom(cls, fileobj, data, mode, memmap, cache, lazy_load_hdus, ignore_missing_simple, **kwargs)
   1088 if not match_sig:
   1089     # Check the SIMPLE card is there but not written correctly
-> 1090     match_sig_relaxed = re.match(rb"SIMPLE\s*=\s*[T|F]", simple)
   1092     if match_sig_relaxed:

File ~/opt/anaconda3/lib/python3.9/re.py:191, in match(pattern, string, flags)
    189 """Try to apply the pattern at the start of the string, returning
    190 a Match object, or None if no match was found."""
--> 191 return _compile(pattern, flags).match(string)

TypeError: cannot use a bytes pattern on a string-like object

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 Heasarc().query_region(coords, mission='swiftuvlog', radius='7 arcmin', fields='All')

File ~/opt/anaconda3/lib/python3.9/site-packages/astroquery/utils/class_or_instance.py:25, in class_or_instance.__get__.<locals>.f(*args, **kwds)
     23 def f(*args, **kwds):
     24     if obj is not None:
---> 25         return self.fn(obj, *args, **kwds)
     26     else:
     27         return self.fn(cls, *args, **kwds)

File ~/opt/anaconda3/lib/python3.9/site-packages/astroquery/utils/process_asyncs.py:29, in async_to_sync.<locals>.create_method.<locals>.newmethod(self, *args, **kwargs)
     27 if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28     return response
---> 29 result = self._parse_result(response, verbose=verbose)
     30 self.table = result
     31 return result

File ~/opt/anaconda3/lib/python3.9/site-packages/astroquery/heasarc/core.py:248, in HeasarcClass._parse_result(self, response, verbose)
    246     return self._fallback(response.text)
    247 except Exception as e:
--> 248     return self._old_w3query_fallback(response.content)

File ~/opt/anaconda3/lib/python3.9/site-packages/astroquery/heasarc/core.py:181, in HeasarcClass._old_w3query_fallback(self, content)
    176 def _old_w3query_fallback(self, content):
    177     # old w3query (such as that used in ISDC) return very strange fits, with all ints
    179     f = fits.open(BytesIO(content))
--> 181     for c in f[1].columns:
    182         if c.disp is not None:
    183             c.format = c.disp

AttributeError: 'ImageHDU' object has no attribute 'columns'

**Comment by bsipocz** [comment] 2023-05-19 16:41
This is a duplicate of #2560 and has been fixed in the dev version.

Could you try and `pip install -U --pre astroquery` and see if it work for you, too?

**Comment by noelklingler** [comment] 2023-05-19 21:09
Hi Brigitta,

Thank you so much for your quick reply and the helpful information.
Indeed, it is working now!  Have a great weekend :)

-Noel

**Closed** 2023-05-19 21:11 UTC
Labels: duplicate, heasarc
