### ISSUE TITLE
Tests failing on SyntaxError in local environment

### ISSUE THREAD

**Issue by tomdonaldson** [astropy/astroquery#1234] opened 2018-09-13 14:06 UTC
When I checkout a clean version of astroquery and try to run the tests within a new conda environment, I get errors trying to import entrypoints from within keyring (SyntaxError:  invalid escape sequence \s).

Using only default channels, here are the steps I tried:
`git clone https://github.com/astropy/astroquery.git`
`conda create -n newenv python=3.6 astropy`
`source activate newenv`
`cd astroquery`
`python setup.py test`

If I force keyring to a previous version, I don't get the syntax errors when I run the tests.  E.g., 
`conda create -n newenv2 python=3.6 astropy keyring=12`

Interestingly, the default conda channel doesn't recognize any keyring version >12, whereas the output from the test runs indicate keyring-15.0.0-py3.6.egg/keyring/...

It's my understanding that '\s' still only warrants a deprecation warning, so maybe something in the test setup is causing that warning to be raised as an error.

`python -c 'print("\s")'`         outputs:
\s

`python -We -c 'print("\s")'`     outputs:
File "<string>", line 1
SyntaxError: invalid escape sequence \s

**Comment by bsipocz** [comment] 2018-09-13 21:46
Thanks, now it's much clearer what the issue is.

> It's my understanding that '\s' still only warrants a deprecation warning, so maybe something in the test setup is causing that warning to be raised as an error.

the test suite is set up to catch deprecation warnings and raise them as exceptions to ensure we catch up with changes early on and not when they are already broken. 
Given we don't have much control over keyring, we need to let this one warning pass.

**Comment by pllim** [comment] 2018-09-14 14:30
The solution is to use raw string, e.g., `r"\s"`.
```
$ python -Wd
Python 3.7.0 | packaged by conda-forge | (default, Aug 27 2018, 18:03:44) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print('\s')
<stdin>:1: DeprecationWarning: invalid escape sequence \s
\s
>>> print(r'\s')
\s
```

**Comment by tomdonaldson** [comment] 2018-09-14 15:01
Yes, but in this case the '\s' is buried in nested imports in keyring, so we can't correct it directly.

I'm still a little confused about how the versioning is handled here with respect to setting up a local test environment that's consistent with what happens when astroquery does its CI.  Is there a recommended way to do this?

I've been manually creating conda environments hoping that they match, but that's just guesswork.  In this case, if I include keyring in my conda create, I get keyring version 12, and the tests run great:
`conda create -n testenv astropy keyring`  
`conda activate testenv`
`python setup.py test`

But if I leave keyring out of that create, keyring version 15 gets installed during the test run, and that version imports the offending '\s'.

**Comment by pllim** [comment] 2018-09-14 15:08
1. Report this upstream to `keyring`
2. Set `astroquery` to ignore deprecation warnings from `keyring`

https://github.com/astropy/astroquery/blob/ce8c500c28424fe841e04741d4230b8f695ee194/astroquery/conftest.py#L35

**Comment by pllim** [comment] 2018-09-17 18:11
Here is the `keyring` repo: https://github.com/jaraco/keyring

As far as I can search, I don't see any open nor closed issues related to this yet. If you decide to open a new issue there, it would be useful to provide them with a minimal code snippet to reproduce that warning, along with a traceback (if any).

**Comment by ViviCoder** [comment] 2021-11-22 19:07
I also get `SyntaxError: invalid escape sequence \s`  when running tests as part of the Debian build process, but it does not seem to be related to keyring.

Here is the full log:
```
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.0

Running tests with Astropy version 4.3.1.
Running tests in .pybuild/cpython3_3.9_astroquery/build.

Date: 2021-11-22T18:50:22

Platform: Linux-5.10.0-9-amd64-x86_64-with-glibc2.32

Executable: /usr/bin/python3.9

Full Python Version: 
3.9.9 (main, Nov 16 2021, 10:24:31) 
[GCC 11.2.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.21.4
Scipy: 1.7.1
Matplotlib: 3.5.0
h5py: not available
Pandas: not available

Using Astropy options: remote_data: none.

rootdir: /build/astroquery-0.4.4+dfsg, configfile: setup.cfg
plugins: mock-3.6.1, hypothesis-5.43.3, openfiles-0.5.0, filter-subpackage-0.1.1, doctestplus-0.11.1, cov-3.0.0, arraydiff-0.3, astropy-header-0.1.2, remotedata-0.3.2
collected 1419 items / 8 errors / 1411 selected

==================================== ERRORS ====================================
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/__init__.py _
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py _
/usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:226: in collect
    module = import_path(fspath)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/setup_package.py _
/usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:226: in collect
    module = import_path(fspath)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/tests/__init__.py _
/usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:226: in collect
    module = import_path(fspath)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/tests/test_ned.py _
/usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:226: in collect
    module = import_path(fspath)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/tests/test_ned.py _
/usr/lib/python3/dist-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/tests/test_ned_remote.py _
/usr/lib/python3/dist-packages/pytest_doctestplus/plugin.py:226: in collect
    module = import_path(fspath)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
_ ERROR collecting .pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/tests/test_ned_remote.py _
/usr/lib/python3/dist-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:972: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
astroquery/ipac/ned/__init__.py:84: in <module>
    from .core import Ned, NedClass
E     File "/build/astroquery-0.4.4+dfsg/.pybuild/cpython3_3.9_astroquery/build/astroquery/ipac/ned/core.py", line 521
E       f'<a\s+href\s*?="?\s*?(.+?{extensions[file_format]})"?\s*?>\s*?(?:Retrieve|{names[file_format]})</a>',
E       ^
E   SyntaxError: invalid escape sequence \s
```

Should I open a separate issue?

**Comment by bsipocz** [comment] 2021-11-23 02:45
Yes, please, this was a recent change in https://github.com/astropy/astroquery/pull/2217, apparently our test wasn't covering this properly to pick the failure up.

**Comment by bsipocz** [comment] 2022-08-09 23:58
I think this issue is not an issue anymore thus closing. Feel free to reopen/open a new one if for some reason you end up running into it again.

**Closed by bsipocz** 2022-08-09 23:58 UTC
Labels: Upstream, infrastructure
