### ISSUE TITLE
BUG: don't cache errors for SkyView

### ISSUE THREAD

**Issue by tvwenger** [astropy/astroquery#1915] opened 2020-12-07 18:11 UTC
I am querying SkyView (WISE 3.4, 12, and 22 data) using an on-sky positions. Occasionally and randomly (as far as I can tell), a query will return an HTTPError: 404 (not found). If I try to run the query again on the machine, then it will fail with the same error. If I add another decimal to the precision of the position, then it will succeed. If I run the original query on a different machine, then it will succeed. For example:

```
from astroquery.skyview import SkyView
import astropy.units as u

# this may fail occasionally and randomly
position = '175.543, -62.336'
images = SkyView.get_images(position=position, coordinates='J2000', pixels=1024, width=0.5*u.deg, survey='WISE 3.4')

# this will succeed (N.B. the extra decimal of precision in the position)
position = '175.5432, -62.3365'
images = SkyView.get_images(position=position, coordinates='J2000', pixels=1024, width=0.5*u.deg, survey='WISE 3.4')
```

It's as if the original query fails for some reason and then that failure is cached. Then, when the same query is called again, the cached failure is returned. Adding another decimal place forces a new query.

**Comment by keflavich** [comment] 2020-12-07 18:13
That's exactly correct: skyview sometimes fails, and (unfortunately) the failures are getting cached.

The solution for now is to delete the failed cached items from `~/.astropy/cache/astroquery/SkyView/`.

**Comment by keflavich** [comment] 2020-12-07 18:15
Duplicate of #1904

**Comment by tvwenger** [comment] 2020-12-07 18:15
@keflavich Awesome, thanks for the lightning fast response and solution.

**Comment by keflavich** [comment] 2020-12-07 18:16
np.  The fact that this is regularly happening suggests we need a better error-catcher in SkyView so we _don't_ cache errors.

**Comment by odysseus9672** [comment] 2021-01-17 06:19
Also duplicate of #1643 .

**Comment by bsipocz** [comment] 2022-11-10 00:06
Hmm, in fact I'll close this as https://github.com/astropy/astroquery/issues/2252 tracking the issue perfectly.

**Closed by bsipocz** 2022-11-10 00:06 UTC
Labels: bug, skyview
