### ISSUE TITLE
Problem with votable repr?

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#559] opened 2015-07-21 14:06 UTC
When I recently tried a `find_table` operation, I got the following traceback from ipython:

```
Out[22]: Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/core/formatters.py", line 690, in __call__
    printer.pretty(obj)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/lib/pretty.py", line 394, in pretty
    return self.type_pprinters[cls](obj, self, cycle)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/lib/pretty.py", line 578, in inner
    p.pretty(x)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/lib/pretty.py", line 394, in pretty
    return self.type_pprinters[cls](obj, self, cycle)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/lib/pretty.py", line 578, in inner
    p.pretty(x)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/lib/pretty.py", line 409, in pretty
    return _default_pprint(obj, self, cycle)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/lib/pretty.py", line 529, in _default_pprint
    _repr_pprint(obj, p, cycle)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/IPython/lib/pretty.py", line 711, in _repr_pprint
    output = repr(obj)
  File "/Users/adam/repos/astropy/astropy/io/votable/tree.py", line 3019, in __repr__
    self._element_name,
AttributeError: 'Resource' object has no attribute '_element_name'
```

which is somehow associated with the repr of the votables being returned.

**Comment by bsipocz** [comment] 2021-11-01 21:37
This is an astropy issue rather than an astroquery. But instead of moving it upstream, I'm closing it as a lot has happened since 2015 and this doesn't seem to resurface again, and there is no code snippet to reproduce.

If you run into it again, please open a new issue with a code snippet in astropy.

**Closed by bsipocz** 2021-11-01 21:37 UTC
Labels: Upstream
