### ISSUE TITLE
HTTP Error 404 For SDSS.get_spectra on BOSS spectra

### ISSUE THREAD

**Issue by sofiapasquini** [astropy/astroquery#1731] opened 2020-06-01 11:16 UTC
Hello!
I am tying to use Astropy.astroquery in a project in order to download spectra from the SDSS database. I am getting the error : HTTP Error 404: Not Found whenever I try to use SDSS.get_spectra() on the matches that I get from query_region() which are spectra taken with the BOSS spectrograph. The code has no problem returning matches from the query, or downloading spectra using SDSS.get_spectra() for spectra which were taken with the SDSS spectrograph. I saw someone had a similar issue a while ago, that there was a binary prefix in the download URL for their BOSS spectra in front of the run2d parameter value, so the spectra could not be downloaded, but I am still having this issue even with the most updated version of astropy. Has anyone else had this issue? Does anyone know of a fix?

**Comment by vedantchandra** [comment] 2020-06-21 20:51
+1, I have the exact same issue on MacOS, using the latest version of astroquery. I can't seem to download any BOSS spectra.

**Comment by keflavich** [comment] 2020-06-21 20:58
Could you provide a minimum working example?  It seems like an upstream issue, possibly a changed URL.

**Comment by vedantchandra** [comment] 2020-06-21 22:58
Sure, here's the relevant code I use:

```
from astroquery.sdss import SDSS
obj = table[0] # say...

xid = SDSS.query_specobj(plate = obj['plate'], mjd = obj['mjd'], fiberID = obj['fiber'])
sp = SDSS.get_spectra(matches=xid)
sp[0].writeto(spec_path + str(objid))
```

This raises an error at the ``SDSS.get_spectra`` step, saying ``HTTPError: HTTP Error 404: Not Found``

**Comment by keflavich** [comment] 2020-06-21 22:59
what is `table` in this context?

**Comment by keflavich** [comment] 2020-06-21 23:01
I'm asking because I need code I can actually run to test this; I don't know what `obj['plate']`, `obj['mjd']`, or `obj['fiber']` should be to reproduce your specific error.

**Comment by vedantchandra** [comment] 2020-06-21 23:03
Of course, my mistake for not providing a runnable example. This exact code reproduces the error:

```
from astroquery.sdss import SDSS
xid = SDSS.query_specobj(plate = 3693, mjd = 55208, fiberID = 144)
sp = SDSS.get_spectra(matches=xid)
sp[0].writeto('sample_path.fits')
```

**Comment by keflavich** [comment] 2020-06-21 23:14
The problem here appears to be that BOSS is renamed EBOSS.  However, it looks like the server is returning the wrong data.

As a hack around this, try:
```
xid.remove_column('instrument')
xid.add_column(name='instrument', col=['eboss'])
```

However, there's not too much we can do about this here, as it is related to an incorrect instrument name in the data returned by `query_specobj`.

**Comment by vedantchandra** [comment] 2020-06-22 09:53
@keflavich That workaround works perfectly! Thank you very much.

**Comment by Nestak2** [comment] 2021-11-16 20:13
@keflavich Is there really not something the astroquery team can do about it? How about hard coding an `if` clause when `HTTPerror` is thrown and then implementing the workaround from above?

**Comment by keflavich** [comment] 2021-11-16 20:24
@Nestak2 No, we can't simply code in an `if` statement here because the same exception will be given for a wide variety of errors, so there is no one fix for this issue.

**Comment by weaverba137** [comment] 2021-11-16 21:04
Funny enough, the logic to fix this already exists: https://github.com/astropy/astroquery/blob/main/astroquery/sdss/core.py#L739, but that applies only to retrieving image data.  This should also be applied to the spectra files.

**Comment by weaverba137** [comment] 2021-11-16 21:14
For spectra, one can also bypass the entire instrument issue by using:
```python
    SPECTRA_URL_SUFFIX = ('{base}/dr{dr}/sdss/spectro/redux/'
                          '{run2d}/spectra/{plate:04d}/'
                          'spec-{plate:04d}-{mjd}-{fiber:04d}.fits')
```
For example https://dr16.sdss.org/sas/dr16/sdss/spectro/redux/ links to all possible `{run2d}` values for DR16.

**Comment by keflavich** [comment] 2021-11-16 22:02
@weaverba137 could you make the change and submit a PR?

**Comment by weaverba137** [comment] 2021-11-16 22:16
Working on it.

**Comment by keflavich** [comment] 2021-11-17 14:04
@Nestak2 this has been fixed - see #2214

**Comment by Nestak2** [comment] 2021-11-17 23:53
@keflavich Thanks, I am working in a google colab editor, so how can I implement the solution? What is the version of astroquery that I need to download to work with it google colab?

**Comment by keflavich** [comment] 2021-11-18 00:15
that branch isn't merged yet, so you can't install the corrected version yet.  You can install that branch, though; see, e.g., [this stackoverflow post](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)

**Comment by Nestak2** [comment] 2021-11-18 19:16
@keflavich Thanks for answering to my question! It seems that I am too unfamiliar with github to manage to install the the correct branch. I read the StackOverflow post you've sent me and tried the following
```
pip install git+https://github.com/astropy/astroquery/pull/2214
pip install git+https://github.com/weaverba137/astroquery/tree/sdss-spectra-url
```
without success. Can you write me what the correct command for downloading the branch is?

**Closed** 2021-11-19 00:04 UTC
Labels: Upstream, sdss
