### ISSUE TITLE
Warning: astroquery.cadc may be using a less than optimal flag for Beautiful Soup

### ISSUE THREAD

**Issue by radioastronomer** [astropy/astroquery#3009] opened 2024-05-17 15:48 UTC
When running cadc.get_data_urls, I get the following warning.

/usr/local/lib/python3.10/dist-packages/astroquery/cadc/core.py:806: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  
Looking at the cadc core code, there is a call on line X:
 soup = BeautifulSoup(response2.text, features="html5lib")
 
 This is clearly the line causing the warning. It is unclear to me whether html5lib or XML is correct. In case of the former, perhaps the BeuatifulSoup warning should be hidden.
   https://stackoverflow.com/questions/33511544/how-to-get-rid-of-beautifulsoup-user-warning

**Comment by bsipocz** [comment] 2024-05-17 21:42
Duplicate of https://github.com/astropy/astroquery/issues/2523

**Closed** 2024-05-17 21:42 UTC
Labels: duplicate

**Comment by bsipocz** [comment] 2024-05-17 21:43
Thanks for opening the issue, it has been on our radar already.
