### ISSUE TITLE
 EOFError while searching the "coordinates",  Irsa.query_region

### ISSUE THREAD

**Issue by wangyj28** [astropy/astroquery#1550] opened 2019-09-18 01:01 UTC
this code works perfectly 
```
from astroquery.irsa import Irsa
from astropy.coordinates import SkyCoord
import astropy.units as u

a = Irsa.query_region("m1", catalog='ptf_lightcurves',radius=1.5*u.arcsec)

print(a)
```

but, when
```
Irsa.query_region(coordinates=SkyCoord('08:22:17.19 +21:37:38.1',unit=(u.hourangle,u.deg)), catalog='ptf_lightcurves',radius=1.5*u.arcsec)
```
 it sudenly crashes with an EOFError.
```
Traceback (most recent call last):

  File "<ipython-input-27-04ee2d6b04e4>", line 1, in <module>
    runfile('/home/wang/literature/ZTF/ZTF.py', wdir='/home/wang/literature/ZTF')

  File "/home/wang/.local/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/wang/.local/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/wang/literature/ZTF/ZTF.py", line 15, in <module>
    catalog='ptf_lightcurves',radius=1.5*u.arcsec)

  File "/usr/local/lib/python3.6/dist-packages/astroquery/irsa/core.py", line 182, in query_region
    selcols=selcols)

  File "/usr/local/lib/python3.6/dist-packages/astroquery/irsa/core.py", line 248, in query_region_async
    params=request_payload, timeout=Irsa.TIMEOUT)

  File "/usr/local/lib/python3.6/dist-packages/astroquery/query.py", line 240, in _request
    response = query.from_cache(self.cache_location)

  File "/usr/local/lib/python3.6/dist-packages/astroquery/query.py", line 103, in from_cache
    response = pickle.load(f)

EOFError: Ran out of input
```

**Comment by wangyj28** [comment] 2019-09-18 01:03
this code works perfectly
`from astroquery.irsa import Irsa
from astropy.coordinates import SkyCoord
import astropy.units as u

a = Irsa.query_region("m1", catalog='ptf_lightcurves',radius=1.5*u.arcsec)

print(a)`

but, when 
`rsa.query_region(coordinates=SkyCoord('08:22:17.19 +21:37:38.1',unit=(u.hourangle,u.deg)), catalog='ptf_lightcurves',radius=1.5*u.arcsec)`

it suddenly crashes with an EOFError.

`Traceback (most recent call last):

File "", line 1, in
runfile('/home/wang/literature/ZTF/ZTF.py', wdir='/home/wang/literature/ZTF')

File "/home/wang/.local/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
execfile(filename, namespace)

File "/home/wang/.local/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)

File "/home/wang/literature/ZTF/ZTF.py", line 15, in
catalog='ptf_lightcurves',radius=1.5*u.arcsec)

File "/usr/local/lib/python3.6/dist-packages/astroquery/irsa/core.py", line 182, in query_region
selcols=selcols)

File "/usr/local/lib/python3.6/dist-packages/astroquery/irsa/core.py", line 248, in query_region_async
params=request_payload, timeout=Irsa.TIMEOUT)

File "/usr/local/lib/python3.6/dist-packages/astroquery/query.py", line 240, in _request
response = query.from_cache(self.cache_location)

File "/usr/local/lib/python3.6/dist-packages/astroquery/query.py", line 103, in from_cache
response = pickle.load(f)

EOFError: Ran out of input`

**Comment by keflavich** [comment] 2019-09-18 16:02
well that's odd.  Try running with `cache=False` and/or delete the cached file.  It looks like the caching operation failed somehow

**Comment by wangyj28** [comment] 2019-09-19 01:06
> well that's odd. Try running with `cache=False` and/or delete the cached file. It looks like the caching operation failed somehow

I try, but it does not work.

**Comment by wangyj28** [comment] 2019-09-19 01:14
> well that's odd. Try running with `cache=False` and/or delete the cached file. It looks like the caching operation failed somehow

how to run `cache=False`?

**Comment by crhea93** [comment] 2020-06-14 23:32
Hi,
 I too am getting this problem. I've tried adding `cache=False`, but it isn't changing anything... Has there been any progress on this?

**Comment by bsipocz** [comment] 2021-07-29 21:44
All of the above examples work for me using a recent astropy and astroquery versions, so I'm closing the issue now (some caching updates were done in astropy since this issue was opened, I suspect those might have provide the fix). Please let us know if you still see the issue, so we could look into reproducing it.

```
In [1]: from astroquery.irsa import Irsa
   ...: from astropy.coordinates import SkyCoord
   ...: import astropy.units as u
   ...: 
   ...: a = Irsa.query_region("m1", catalog='ptf_lightcurves',radius=1.5*u.arcsec)
   ...: 
   ...: print(a)
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.irsa.core]
obsmjd mag_autocorr magerr_auto oid    ra     dec   clon clat ... qaflags flags photcalflag   goodflag  pid  dist  angle
 days      mag          mag         degrees degrees           ...               0=No, 1=Yes 0=No, 1=Yes     arcsec  deg 
------ ------------ ----------- --- ------- ------- ---- ---- ... ------- ----- ----------- ----------- --- ------ -----

In [2]: Irsa.query_region(coordinates=SkyCoord('08:22:17.19 +21:37:38.1',unit=(u.hourangle,u.deg)), catalog='ptf_lightcurves',r
   ...: adius=1.5*u.arcsec)
Out[2]: 
<Table length=10>
     obsmjd      mag_autocorr magerr_auto       oid             ra     ... photcalflag   goodflag    pid     dist     angle  
      days           mag          mag                        degrees   ... 0=No, 1=Yes 0=No, 1=Yes          arcsec     deg   
    float64        float64      float64        int64         float64   ...    int32       int32     int32  float64   float64 
---------------- ------------ ----------- ---------------- ----------- ... ----------- ----------- ------- -------- ---------
 55591.222787200       18.303       0.166 1000332025019631 125.5716510 ...           0           1 9901608 0.131699 32.199842
 55591.267257200       18.574       0.167 1000332025019631 125.5716510 ...           0           1 9901771 0.131699 32.199842
 55591.424737200       19.503       0.172   36612015010007 125.5716480 ...           0           1 9900968 0.274532   12.7414
 55591.298507200       19.109       0.218   36612015010007 125.5716480 ...           0           1 9901098 0.274532   12.7414
 55591.406387200       19.438       0.171   36612015010007 125.5716480 ...           0           1 9901132 0.274532   12.7414
 55591.253597200       18.592       0.160   36612015010007 125.5716480 ...           0           1 9900962 0.274532   12.7414
 55591.268347200       18.687       0.160   36612015010007 125.5716480 ...           0           1 9900960 0.274532   12.7414
 55591.220597200       18.310       0.159   36612015010007 125.5716480 ...           0           1 9900958 0.274532   12.7414
 55591.234247200       18.415       0.159   36612015010007 125.5716480 ...           0           1 9900929 0.274532   12.7414
 55591.440117200       19.574       0.177   36612015010007 125.5716480 ...           0           1 9900927 0.274532   12.7414
```

**Closed by bsipocz** 2021-07-29 21:44 UTC
Labels: irsa
