### ISSUE TITLE
Simbad import broken with astropy v4.0

### ISSUE THREAD

**Issue by hover2pi** [astropy/astroquery#1621] opened 2020-01-23 19:29 UTC
Since `astropy` v4.0 removed `astropy.extern.six`, importing the `simbad` module (e.g. `from astroquery.simbad import Simbad`) throws `ModuleNotFoundError: No module named 'astropy.extern.six'`.

Any plans to update this soon so `astroquery` works with `astropy` v4.0? Thanks!

**Comment by bsipocz** [comment] 2020-01-23 19:48
This is a duplicate of https://github.com/astropy/astroquery/issues/1537

I suspect you are not using the latest version, please update. (However a new tagged release is also in the works to ship some more new functionality).

**Closed by bsipocz** 2020-01-23 19:48 UTC
