### ISSUE TITLE
ALMA remote tests: more files disappeared

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1738] opened 2020-06-09 14:32 UTC
One of the ALMA remote tests is now failing because two more files disappeared out of the archive:
```
__________________________________________________________________________________________________________ TestAlma.test_query ___________________________________________________________________________________________________________

self = <astroquery.alma.tests.test_alma_remote.TestAlma object at 0xb2682ceb8>, temp_dir = '/var/folders/_r/c4nkvmpn4vx6qc91qygz8h740000gt/T/tmp4hvf90jt'

    def test_query(self, temp_dir):
        alma = Alma()
        alma.cache_location = temp_dir

        result = alma.query(payload={'start_date': '<11-11-2011'},
                            public=False, science=True)
        # Nov 16, 2016: 159
        # Apr 25, 2017: 150
        # Jul 2, 2017: 160
        # May 9, 2018: 162
        # March 18, 2019: 171 (seriously, how do they keep changing history?)
>       assert len(result) == 171
E       assert 169 == 171
E        +  where 169 = len(<Table length=169>\n  Project code        Source name        ... ASA_PROJECT_CODE\n                                     ....0.00005.SV                     SgrA ...  2011.0.00005.SV\n2011.0.00001.SV                   TW Hya ...  2011.0.00001.SV)

astroquery/alma/tests/test_alma_remote.py:198: AssertionError
======================================================================================================== short test summary info =========================================================================================================
FAILED astroquery/alma/tests/test_alma_remote.py::TestAlma::test_query - assert 169 == 171
```

note the frustrated comment above the failing line.  I'll just change this number, but I'm seriously concerned about what this implies for the stability of archival data.

**Comment by bsipocz** [comment] 2020-06-12 03:27
This also comes up on the webquery right? So it's more like a serious reproducible issue on the archive side rather than something we can do anything about on our end. So maybe we should just simply require it to be between 150 and 171; report is upstream and call it a day?

**Comment by keflavich** [comment] 2020-06-12 12:13
yes, this is upstream.   I want to change it to 169 so we have a log over the years of disappearing data.

**Comment by bsipocz** [comment] 2022-02-25 06:04
This test has been refactored since this issue, so I'm closing. There are some other remote data tests failing, but they are different in nature so not worth reusing this issue.

**Closed by bsipocz** 2022-02-25 06:04 UTC
Labels: Upstream, alma
