### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by Toma-Bad** [astropy/astroquery#693] opened 2016-05-30 09:21 UTC
Hi all,

While attempting to download public Alma data, i get this error. 
I'm logging in using my alma username and password, and i'm downloading only public data. I'm not 
very good with python yet, and i couldn't find help with this error message related to astroquery anywhere.

> Traceback (most recent call last):
>   File "./cosmos_alma_download_and_extract.py", line 21, in <module>
>     myAlma.download_files(link_list, cache=True)
>   File "/export/archive2/cosmos/alma_archive/astroquery/astroquery/alma/core.py", line 341, in download_files
>     timeout=self.TIMEOUT, cache=cache)
>   File "/export/archive2/cosmos/alma_archive/astroquery/astroquery/query.py", line 162, in _request
>     auth=auth, cache=cache)
>   File "/export/archive2/cosmos/alma_archive/astroquery/astroquery/query.py", line 190, in _download_file
>     response.raise_for_status()
>   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized

**Comment by bsipocz** [comment] 2016-05-30 12:13
@blakut - Could you please post the commands that produced this traceback? I'll try to reproduce it locally. Also I wonder which version of astroquery you use? Please run the following in your python interpreter:

```
import astroquery
astroquery.__version__
```

**Comment by blakut** [comment] 2016-05-30 12:21
Hi, yes:

```
#!/usr/bin/python
from astropy import coordinates
from astroquery.alma import Alma
from astropy import units as u
import numpy as np

cosmos_center = coordinates.SkyCoord(+150.119166*u.deg,+2.205833*u.deg,frame='fk5')
cos_data = Alma.query_region(cosmos_center,2*u.deg,public=True,science=True)
uids = np.unique(cos_data['Member ous id'])
link_list = Alma.stage_data(uids)
myAlma = Alma()
myAlma.login("toma")
myAlma.cache_location = '/export/archive2/cosmos/alma_archive/'
link_list = list(set(link_list['URL']))
myAlma.TIMEOUT = 240

myAlma.download_files(link_list, cache=True)
```

the version is:
0.3.2.dev3248
It is installed locally, since i'm not root, and with the 3.1 version i got other errors from trying to stage data.

**Comment by blakut** [comment] 2016-05-30 12:22
It works for some time, but then at some point it stops with the error i posted initially. I re-run it, and it works again for some time.

**Comment by keflavich** [comment] 2016-05-31 07:10
@blakut - this sounds like a known error in which it is not possible to query for the same data set twice with a single instance of an `Alma` astroquery object.  I still don't understand the nature of the issue; it is something weird about how the servers operate.  

The new part of this is that you're receiving an Error 401; I've seen this happen before with Error 405, and astroquery raises the appropriate error:
```
                            "Received an error 405: this may indicate you "
                            "have already staged the data.  Try downloading "
                            "the file URLs directly with download_files."
```
Repeating a query and getting a 401 is an interesting new one... I'll see if I can reproduce it, and if I can, we'll either fix it or raise a more helpful error.

**Comment by bsipocz** [comment] 2021-11-02 08:52
The alma module has got a full refactor following a remote service API change, so I'm closing this issue as it's very likely not relevant anymore. Please do reopen if you still encounter anything similar.

**Closed by bsipocz** 2021-11-02 08:52 UTC
Labels: alma
