### ISSUE TITLE
cadc package: query_region radius argument does not work with `astropy.units.Quantity`

### ISSUE THREAD

**Issue by ellieb** [astropy/astroquery#1440] opened 2019-05-10 18:17 UTC
Using the CADC package. Running `query_region` with radius argument as a float/int seems to work fine, however using astropy units for radius does not work.

So this works:
```
from astroquery.cadc import Cadc
from astropy.coordinates import SkyCoord
from astropy import units as u
cadc = Cadc()

c = SkyCoord(ra=127.5* u.deg, dec=4.3* u.deg, frame='icrs')
cadc.query_region(c, radius=1)
```

But running this
```
cadc.query_region(c, radius=1*u.deg)
```
gives a Bad Request error:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-68-f4c802433ee1> in <module>
----> 1 cadc.query_region(c, radius=1*u.deg)

~/anaconda3/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

~/anaconda3/lib/python3.7/site-packages/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     24             verbose = kwargs.pop('verbose', False)
     25 
---> 26             response = getattr(self, async_method_name)(*args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response

~/anaconda3/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

~/anaconda3/lib/python3.7/site-packages/astroquery/cadc/core.py in query_region_async(self, coordinates, radius, collection, get_query_payload)
    165         if get_query_payload:
    166             return request_payload
--> 167         response = self.run_query(request_payload['query'], operation='sync')
    168         return response
    169 

~/anaconda3/lib/python3.7/site-packages/astroquery/cadc/core.py in run_query(self, query, operation, output_file, output_format, verbose, background, upload_resource, upload_table_name)
    346                 dump_to_file=save_to_file,
    347                 upload_resource=upload_resource,
--> 348                 upload_table_name=upload_table_name)
    349             op = False
    350         elif operation == 'async':

~/anaconda3/lib/python3.7/site-packages/astroquery/utils/tap/core.py in launch_job(self, query, name, output_file, output_format, verbose, dump_to_file, upload_resource, upload_table_name)
    239             if dump_to_file:
    240                 self.__connHandler.dump_to_file(suitableOutputFile, response)
--> 241             raise requests.exceptions.HTTPError(response.reason)
    242         else:
    243             if verbose:

HTTPError: Bad Request
```

**Comment by keflavich** [comment] 2019-05-10 18:25
I believe this is a duplicate of https://github.com/astropy/astroquery/pull/1437, but it's helpful to have this as a separate issue.  cc @andamian

**Comment by bsipocz** [comment] 2019-09-19 00:14
#1507 has fixed this.

**Closed by bsipocz** 2019-09-19 00:14 UTC
Labels: bug, cadc
