### ISSUE TITLE
Cparser Error When Utilizing astroquery.sdss query_region

### ISSUE THREAD

**Issue by cmistick** [astropy/astroquery#2964] opened 2024-03-05 23:54 UTC
### Description

In Astroquery.sdss, the method query_region now results in an error that prevents the query from running:

astropy/io/ascii/cparser.pyx in astropy.io.ascii.cparser.CParser.read()

InconsistentTableError: Number of header columns (1) inconsistent with data columns in data line 13. 

This also occurs when running the query on just a coordinate, not even a table. The errors started after the cparser.pyx update last week.

**Comment by pllim** [comment] 2024-03-06 00:02
What does "cparser.pyx update" mean? Did you upgrade `astropy` without upgrading also `astroquery`? I have transferred this issue to `astroquery` to make sure it is not a `sdss` problem first. Thanks!

**Comment by cmistick** [comment] 2024-03-06 00:18
> What does "cparser.pyx update" mean? Did you upgrade `astropy` without upgrading also `astroquery`? I have transferred this issue to `astroquery` to make sure it is not a `sdss` problem first. Thanks!

I mean that within Astropy / io / ascii, cparser.pyx seems to be the cause of this error that stops the query from running. I haven't upgraded anything, I have just tried to run code that previously worked last week prior to the addition of cparser.pyx. Thanks!

**Comment by pllim** [comment] 2024-03-06 01:33
> worked last week prior to the addition of cparser.pyx

This does not quite make sense to me because everything in `astropy.io.ascii` (including `Cparser`) comes installed with `astropy`. If you have not upgraded `astropy` prior to the failure, then it could not have been due to any changes in this `Cparser`. I suspect `sdass` instead.

**Comment by keflavich** [comment] 2024-03-06 02:29
As far as I can tell, SDSS is working just fine:
```python
>>> SDSS.query_region(SkyCoord(0*u.deg, 0*u.deg), radius=10*u.arcsec)
<Table length=2>
         ra                 dec                 objid         run  rerun camcol field
      float64             float64               uint64       int64 int64 int64  int64
------------------- -------------------- ------------------- ----- ----- ------ -----
0.00104056324977364 -0.00152783670768634 1237660008400880014  3384   301      3   369
   359.998882460665 -0.00116745931846608 1237645877945303463    94   301      3   168

>>> astroquery.__version__
'0.4.7.dev9039'
>>> astropy.__version__
'6.0.0'
```
and the only recent changes to SDSS are documentation changes:
https://github.com/astropy/astroquery/commits/main/astroquery/sdss/core.py

I suspect instead this is a failed install.

@cmistick Please provide a complete example and a full traceback, we're just guessing at your problem because you haven't provided enough information yet.

**Comment by cmistick** [comment] 2024-03-06 02:41
> @cmistick Please provide a complete example and a full traceback, we're just guessing at your problem because you haven't provided enough information yet.

Here is an example with traceback. Thanks for your help!

from astropy.io import fits
from astropy import units
from astropy.table import Table
import astropy.units as u
import numpy as np, pandas as pd
!pip install --pre astroquery
from astropy import coordinates
from astropy.coordinates import SkyCoord
from astroquery.sdss import SDSS
from astropy import constants as const
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=70, Om0=0.3, Tcmb0=2.725)
import pickle
pickle.HIGHEST_PROTOCOL = 4
import math
import matplotlib.pyplot as plt
(We're importing a lot of packages because this is just copied code used elsewhere in the project)

from google.colab import drive
drive.mount('/content/gdrive')

Cluster_data = Table(fits.open('/content/gdrive/catCluster-SPIDERS_RASS_CLUS-v3.0.fits')[1].data).to_pandas()
BCG_data     = Table(fits.open('/content/gdrive/SpidersXclusterBCGs-v2.0.fits')[1].data).to_pandas()
Joined_data = pd.merge(Cluster_data, BCG_data, on = 'CLUS_ID', how = 'inner')

coord = SkyCoord(Joined_data['RA'], Joined_data['DEC'], unit='deg')
SDSS.query_region(coord[0], spectro = True, width = '20 arcmin')


WARNING: Field info are not available for this data release [astroquery.sdss.field_names]
WARNING:astroquery:Field info are not available for this data release
WARNING: Field info are not available for this data release [astroquery.sdss.field_names]
WARNING:astroquery:Field info are not available for this data release

---------------------------------------------------------------------------

InconsistentTableError                    Traceback (most recent call last)

<ipython-input-7-9a970141a1a5> in <cell line: 1>()
----> 1 SDSS.query_region(coord[0], spectro = True, width = '20 arcmin')

7 frames

/usr/local/lib/python3.10/dist-packages/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

/usr/local/lib/python3.10/dist-packages/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response
---> 29             result = self._parse_result(response, verbose=verbose)
     30             self.table = result
     31             return result

/usr/local/lib/python3.10/dist-packages/astroquery/sdss/core.py in _parse_result(self, response, verbose)
   1040                 warnings.filterwarnings("ignore", category=AstropyWarning,
   1041                                         message=r'OverflowError converting to IntType in column.*')
-> 1042             arr = Table.read(response.text, format='ascii.csv', comment="#")
   1043             for id_column in ('objid', 'specobjid', 'objID', 'specobjID', 'specObjID'):
   1044                 if id_column in arr.columns:

/usr/local/lib/python3.10/dist-packages/astropy/table/connect.py in __call__(self, *args, **kwargs)
     60         descriptions = kwargs.pop("descriptions", None)
     61 
---> 62         out = self.registry.read(cls, *args, **kwargs)
     63 
     64         # For some readers (e.g., ascii.ecsv), the returned `out` class is not

/usr/local/lib/python3.10/dist-packages/astropy/io/registry/core.py in read(self, cls, format, cache, *args, **kwargs)
    216 
    217             reader = self.get_reader(format, cls)
--> 218             data = reader(*args, **kwargs)
    219 
    220             if not isinstance(data, cls):

/usr/local/lib/python3.10/dist-packages/astropy/io/ascii/connect.py in io_read(format, filename, **kwargs)
     17         format = re.sub(r"^ascii\.", "", format)
     18         kwargs["format"] = format
---> 19     return read(filename, **kwargs)
     20 
     21 

/usr/local/lib/python3.10/dist-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    391             fast_reader_rdr = get_reader(**fast_kwargs)
    392             try:
--> 393                 dat = fast_reader_rdr.read(table)
    394                 _read_trace.append(
    395                     {

/usr/local/lib/python3.10/dist-packages/astropy/io/ascii/fastbasic.py in read(self, table)
    151 
    152         with _set_locale("C"):
--> 153             data, comments = self.engine.read(try_int, try_float, try_string)
    154         out = self.make_table(data, comments)
    155 

astropy/io/ascii/cparser.pyx in astropy.io.ascii.cparser.CParser.read()

InconsistentTableError: Number of header columns (1) inconsistent with data columns in data line 13

**Comment by cmistick** [comment] 2024-03-06 03:27
I'm not sure what astropy version it's using, only that I'm importing it as above and I'm working in Google Colab.
As far as the coordinate, it is <SkyCoord (ICRS): (ra, dec) in deg (119.91947, 54.009942)>

**Comment by MridulS** [comment] 2024-03-06 13:23
You can quickly find the astropy version by running:

```python
import astropy
print(astropy.__version__)
```

inside one of the cells of your google colab notebook.

**Comment by pllim** [comment] 2024-03-06 14:31
Google Collab... Are you able to reproduce this error locally?

**Closed** 2024-03-06 18:47 UTC
Labels: bug, sdss
