### ISSUE TITLE
EOFError while searching the identifiers of a star

### ISSUE THREAD

**Issue by Titanosaurus** [astropy/astroquery#966] opened 2017-08-08 20:45 UTC
Basically, this code works perfectly for tens of thousands of entries.
```python
from astroquery.simbad import Simbad
Simbad.query_objectids(name)
```
But when ```name="TYC 1235-274-1"``` it sudenly crashes with an EOFError. The star [has an entry](http://simbad.u-strasbg.fr/simbad/sim-id?Ident=TYC+1235-274-1&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id) in Simbad. Why is this happening?

**Comment by bsipocz** [comment] 2017-08-08 20:55
@Titanosaurus - What is your version number for astroquery? Your example works for me on master:

```
In [1]: from astroquery.simbad import Simbad

In [2]: name="TYC 1235-274-1" 

In [3]: Simbad.query_objectids(name)
Out[3]: 
<Table length=10>
           ID          
        bytes23        
-----------------------
 Gaia 41615037642583808
2MASS J03381654+1510167
             AG+15  310
            BD+14   587
        GSC 01235-00274
              HD  22555
             PPM 119240
             SAO  93527
         TYC 1235-274-1
           YZ  15  1057

In [4]: import astroquery

In [5]: astroquery.__version__
Out[5]: '0.3.7.dev4056'
```

**Comment by Titanosaurus** [comment] 2017-08-08 21:02
Thank you bsipocz for the quick answer.

Mine is this:

```python
import astroquery
astroquery.__version__
u'0.3.6.post2'
```

**Comment by bsipocz** [comment] 2017-08-08 21:06
can you post the full traceback?

**Comment by aoberto** [comment] 2017-08-08 21:08
May be because there is a limitation to a list of 10 000 rows !

Anais

**Comment by Titanosaurus** [comment] 2017-08-09 07:01
> can you post the full traceback?

Sure. Here it is:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\astroquery\simbad\core.py", line 794, in query_objectids
    result = self.query_objectids_async(object_name)
  File "C:\Python27\lib\site-packages\astroquery\simbad\core.py", line 817, in query_objectids_async
    timeout=self.TIMEOUT, cache=cache)
  File "C:\Python27\lib\site-packages\astroquery\query.py", line 199, in _request
    response = query.from_cache(self.cache_location)
  File "C:\Python27\lib\site-packages\astroquery\query.py", line 98, in from_cache
    response = pickle.load(f)
  File "C:\Python27\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by bsipocz** [comment] 2017-08-09 11:14
How many objects do you have in total? Do you see the issue when only running the query for this single one object?
I'm still unable to reproduce this, and the case @aoberto suggests is very plausible.

**Comment by keflavich** [comment] 2017-08-09 13:04
That traceback indicates a bad cache file, no?  Try removing your cached SIMBAD queries.

**Comment by bsipocz** [comment] 2022-11-09 19:11
Closing as could not reproduce and it likely was a cache issue.

**Closed by bsipocz** 2022-11-09 19:11 UTC
Labels: simbad
