### ISSUE TITLE
ImportError: No module named version_helpers

### ISSUE THREAD

**Issue by AlexaVillaume** [astropy/astroquery#598] opened 2015-10-23 16:14 UTC
Hello,

I've been trying to set up astroquery on a new machine (I had it installed on an old computer and it worked fine) but I can't get it working. There might be two problems:

I have the anaconda version of astropy installed on a mac. Astroquery appears not to come with astropy since if I just try to use the astropy as-is I get an error that says the astroquery module doesn't exist when I import try to import it. 

I also pulled astroquery from github and when I try to import an astroquery class I get the following error,

``` from astroquery.irsa import Irsa```

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "astroquery/irsa/__init__.py", line 37, in <module>
    from .core import Irsa, IrsaClass
  File "astroquery/irsa/core.py", line 101, in <module>
    from ..query import BaseQuery
  File "astroquery/query.py", line 16, in <module>
    from . import version
  File "astroquery/version.py", line 3, in <module>
    from astropy.version_helpers import update_git_devstr, get_git_devstr
ImportError: No module named version_helpers```

I've tried this from Vizier and Simbad as well and get the same error. However, ```import astroquery``` appears to work fine. 

Can anyone explain this error?

Thank you,
Alexa

**Comment by bsipocz** [comment] 2015-10-23 16:22
@AlexaVillaume - astroquery is not on conda, and is an affiliated package (thus not part of the core astropy you installed from conda). Have you tried to pip install it? Do you still see the error? 

http://astroquery.readthedocs.org/en/latest/#installation

**Comment by AlexaVillaume** [comment] 2015-10-23 17:44
Using pip install works. But is there any reason that installing from github shouldn't work?

**Comment by bsipocz** [comment] 2015-10-26 11:44
It should work, too. Did you follow the installation guide for that? (same link as above).

**Comment by bsipocz** [comment] 2015-10-27 17:05
Closing this as it works as the recommended way works as it supposed to be and I cannot reproduce the problem.

@AlexaVillaume please feel free to give more details about the way you installed the "github" version, and thus we can try to figure out where it went wrong.

**Closed by bsipocz** 2015-10-27 17:05 UTC
