### ISSUE TITLE
SDSS.query_region gives error in astroquery 0.4.7.dev8076

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#2653] opened 2023-01-31 14:13 UTC
This error does not happen in astroquery 0.4.6. To reproduce this error:

```python
from astropy.coordinates import SkyCoord
from astropy import units as u

c = SkyCoord(6.62754354, 1.54466139, unit='deg')
r = 3 * u.arcmin

query_region_result = SDSS.query_region(c, radius=r, data_release=17)
```

```
File astroquery/utils/class_or_instance.py:25, in class_or_instance.__get__.<locals>.f(*args, **kwds)
     23 def f(*args, **kwds):
     24     if obj is not None:
---> 25         return self.fn(obj, *args, **kwds)
     26     else:
     27         return self.fn(cls, *args, **kwds)

File astroquery/utils/process_asyncs.py:29, in async_to_sync.<locals>.create_method.<locals>.newmethod(self, *args, **kwargs)
     27 if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28     return response
---> 29 result = self._parse_result(response, verbose=verbose)
     30 self.table = result
     31 return result

File astroquery/sdss/core.py:905, in SDSSClass._parse_result(self, response, verbose)
    903 if response.content.startswith(b'#Table'):
    904     skip_header = 1
--> 905 arr = np.atleast_1d(np.genfromtxt(io.BytesIO(response.content),
    906                                   names=True, dtype=None,
    907                                   delimiter=',', skip_header=skip_header,
    908                                   comments='#'))
    910 if len(arr) == 0:
    911     return None

File numpy/lib/npyio.py:2301, in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, ndmin, like)
   2299 # Raise an exception ?
   2300 if invalid_raise:
-> 2301     raise ValueError(errmsg)
   2302 # Issue a warning ?
   2303 else:
   2304     warnings.warn(errmsg, ConversionWarning, stacklevel=2)

ValueError: Some errors were detected !
    Line #3 (got 3 columns instead of 1)
    Line #5 (got 3 columns instead of 1)
    Line #6 (got 4 columns instead of 1)
    Line #8 (got 4 columns instead of 1)
    Line #12 (got 4 columns instead of 1)
    Line #15 (got 6 columns instead of 1)
    Line #17 (got 4 columns instead of 1)
    Line #21 (got 3 columns instead of 1)
    Line #31 (got 2 columns instead of 1)
```

**Comment by pllim** [comment] 2023-01-31 14:13
In case it matters, numpy is 1.24.1

**Comment by keflavich** [comment] 2023-01-31 14:19
I can reproduce this.  @weaverba137 do you have any insight into this issue?

**Comment by weaverba137** [comment] 2023-01-31 14:21
I believe this is a duplicate, and I'm already in contact with the SDSS team to see if anything has changed on their end.

**Comment by keflavich** [comment] 2023-01-31 14:23
Yes, duplicate of https://github.com/astropy/astroquery/issues/2644, thanks for noting that.

**Comment by keflavich** [comment] 2023-01-31 14:24
@pllim Thanks for reporting; I'm closing as a duplicate of #2644.  Further discussion should go there.

**Closed by keflavich** 2023-01-31 14:24 UTC
Labels: bug, sdss, Affects-dev
