### ISSUE TITLE
catalog option no longer working in VizieR

### ISSUE THREAD

**Issue by rickyegeland** [astropy/astroquery#1237] opened 2018-09-17 22:55 UTC
I am using astroquery 0.3.8.  The `catalog=` parameter does not appear to be restricting the catalogs output by `query_object()` or `query_region()`.  Here is an example adapted from the [documentation](https://astroquery.readthedocs.io/en/latest/vizier/vizier.html):

```python
>>> v = astroquery.vizier.Vizier(columns=["*", "+_r"], catalog="II/246")
>>> result = v.query_region("HD 226868", radius="20s")
>>> print(result)
```

Output:
```
TableList with 218 tables:
	'0:METAobj' with 6 column(s) and 7 row(s) 
	'1:ReadMeObj' with 6 column(s) and 7 row(s) 
	'2:I/61B/agk3' with 16 column(s) and 1 row(s) 
	'3:I/122/bd' with 10 column(s) and 1 row(s) 
	'4:I/131A/sao' with 12 column(s) and 1 row(s) 
...etc
```

I have tried several `catalog=` values and the result is the same.  It seems the parameter is just being ignored.

**Comment by jwoillez** [comment] 2020-04-17 11:43
@bsipocz I cannot reproduce this bug with the current version. Close?

**Comment by keflavich** [comment] 2020-04-17 12:56
Closing.  Please open a new issue if you encounter this behavior again.

**Closed by keflavich** 2020-04-17 12:56 UTC
Labels: bug, vizier
