### ISSUE TITLE
ESO retrieve data - Files keep failing

### ISSUE THREAD

**Issue by jorgehumberto** [astropy/astroquery#1360] opened 2019-02-18 04:07 UTC
HI,

I am attempting to download some ESPRESSO data from ESO's archive via the comment line using astroquery. To do so, I did the folowing (as per ESO's Support suggestion):

1. Install astroquery
2. find its location in the python path (look for the directory: site-packages/astroquery/eso)
3. create a parallel directory astroquery/esocas
4. copy the content of astroquery/eso/ into astroquery/esocas
5. modify astroquery/esocas by editing both the core.py and the __init__.py
         and replace any wdb/wdb/eso with wdb/wdb/cas

 
To query the ESO server, I use:

    from astroquery.esocas import Eso

    eso = Eso()

    eso.ROW_LIMIT = -1

    eso.USERNAME = username

    eso.login(username, store_password=True)

    query_results = eso.query_instrument('ESPRESSO', column_filters={'night':NIGHT, 'dp_cat':'SCIENCE'}, cache= False)

    data_files = eso.retrieve_data(query_results['DP.ID'], with_calib='raw', destination=DATA_ROOT request_all_objects = True)

The problem I am facing is that sometimes the download fails on specific files when doing the above, although I am able to download them when I use the web interface. 

For example when selecting `NIGHT = '2018-09-01'`, the download consistently failed at filename "ESPRE.2018-09-05T18:26:46.039.fits.Z", multiple times during the same night/over several hours.

here is the error:

    Traceback (most recent call last):

      File "dl_from_eso_archive.py", line 176, in <module>

        main()

      File "dl_from_eso_archive.py", line 121, in main

        data_files = eso.retrieve_data(query_results['DP.ID'], with_calib='raw', destination=DATA_ROOT request_all_objects = True)

      File "/opt/anaconda3/envs/esoPy/lib/python3.7/site-packages/astroquery/esocas/core.py", line 720, in retrieve_data

        state = root.select('span[id=requestState]')[0].text

    IndexError: list index out of range

I also had cases where the downloaded file was not a fits.Z file, but a bank login webpage, so I guess the connection somehow timed out? 

Any idea what is happening?

PS: not sure if it help/causes issues, but I normally run the code inside "screen".

**Comment by keflavich** [comment] 2019-02-18 12:46
A few comments:
-screen won't affect anything
-you can modify URLs interactively, you don't need to edit the code.  e.g.:
```
from astroquery.eso import Eso
Eso.QUERY_INSTRUMENT_URL = 'http://archive.eso.org/wdb/wdb/cas'
```

However, I don't know what's causing your particular issue.  It could be that the login is timing out.  Are these data proprietary?  Could you retry your whole query using the approach I suggest above and post your code here?

**Comment by jorgehumberto** [comment] 2019-02-18 22:26
Hi @keflavich 

1. I suspected about screen, but just in case... 

2. Thanks about the tip to modify the URl interactively! I'll give it a try.

3. Yes, the data is proprietary, but it is not a credentials issue as it downloads most files from the same programme/dataset, but fails alsays on the same file.

4. I also don't it is a login timeout, as if can fail after a long time, or a short one, and always on the same file for a given night.

I'll give a try to the change URL approach and post the code tomorrow when I get to work.

Thanks!!

**Comment by jorgehumberto** [comment] 2019-02-19 15:46
Hi @keflavich 


Here is a MWE of my code with the interactive URL:

    #!/usr/bin/env python
    
    from astroquery.eso import Eso
    import os
    
    INSTRUMENT = 'ESPRESSO'
    NIGHT = '2018-09-01'
    CATG='SCIENCE'
    DATA_FOLDER = '/home/espresso/work/ESPRESSO_RAW'
    USER = 'XXX'
    
    eso = Eso()
    eso.ROW_LIMIT = -1
    eso.QUERY_INSTRUMENT_URL = 'http://archive.eso.org/wdb/wdb/cas'
    eso.login(USER, store_password=True)
    query_results = eso.query_instrument(INSTRUMENT, column_filters={'night':NIGHT, 'dp_cat':CATG}, cache= False)
    
    file_list = query_results['DP.ID']
    
    data_files = eso.retrieve_data(query_results['DP.ID'], with_calib='raw', destination=os.path.abspath('{}/{}'.format(DATA_FOLDER,NIGHT)), request_all_objects = True)


and here is the error/output I get now:

    INFO: Authenticating XXX on www.eso.org... [astroquery.eso.core]
    INFO: Authentication successful! [astroquery.eso.core]
    INFO: Checking availability of datasets to download... [astroquery.eso.core]
    INFO: Downloading datasets... [astroquery.eso.core]
    INFO: Contacting retrieval server... [astroquery.eso.core]
    INFO: Staging request... [astroquery.eso.core]
    INFO: Staging form is at http://dataportal.eso.org/rh/requests/XXX/403232 [astroquery.eso.core]
    Traceback (most recent call last):
      File "test.py", line 20, in <module>
        data_files = eso.retrieve_data(query_results['DP.ID'], with_calib='raw', destination=os.path.abspath('{}/{}'.format(DATA_FOLDER,NIGHT)), request_all_objects = True)
      File "/opt/anaconda3/envs/esoPy/lib/python3.7/site-packages/astroquery/eso/core.py", line 720, in retrieve_data
        state = root.select('span[id=requestState]')[0].text
    IndexError: list index out of range


When I use the "esocas" approach:

    from astroquery.esocas	 import Eso

I get a different error:

    INFO: Authenticating XXX on www.eso.org... [astroquery.eso.core]
    INFO: Authentication successful! [astroquery.eso.core]
    INFO: Checking availability of datasets to download... [astroquery.eso.core]
    INFO: Downloading datasets... [astroquery.eso.core]
    INFO: Contacting retrieval server... [astroquery.eso.core]
    INFO: Staging request... [astroquery.eso.core]
    INFO: Staging form is at http://dataportal.eso.org/rh/requests/XXX/403245 [astroquery.esocas.core]
    INFO: Detecting already downloaded datasets, including calibrations... [astroquery.esocas.core]
    INFO: Found ESPRE.2018-09-05T23:19:55.097.fits.Z.fits.Z... [astroquery.esocas.core]
    INFO: Found ESPRE.2018-09-09T11:01:31.371.fits.Z.fits.Z... [astroquery.esocas.core]

[...]
**_a bunch of filenames_**
[...]

    INFO: Found ESPRE.2018-09-05T18:05:36.102.fits.Z.fits.Z... [astroquery.esocas.core]
    INFO: Downloading 81 files... [astroquery.esocas.core]
    INFO: Downloading file 1/81: ESPRE.2018-09-01T23:43:43.061.xml... [astroquery.esocas.core]

[...]
**_a bunch of filenames_**
[...]

    Downloading URL https://dataportal.eso.org/dataPortal/requests/XXX/403245/STAGING/ESPRE.2018-09-01T23:12:03.582.AT/ESPRE.2018-09-01T23:12:03.582.xml to /home/espresso/.astropy/cache/astroquery/Eso/ESPRE.2018-09-01T23:12:03.582.xml ... [Done]

    INFO: Copying file ESPRE.2018-09-01T23:12:03.582.xml to /home/espresso/work/ESPRESSO_RAW/2018-09-01... [astroquery.esocas.core]
    INFO: Downloading file 3/81: ESPRE.2018-09-05T18:26:46.039.fits.Z... [astroquery.esocas.core]
    Traceback (most recent call last):
      File "test.py", line 25, in <module>
        data_files = eso.retrieve_data(file_list, with_calib='raw', destination=DATA_FOLDER, request_all_objects = True)
      File "/opt/anaconda3/envs/esoPy/lib/python3.7/site-packages/astroquery/esocas/core.py", line 783, in retrieve_data
        continuation=True)
      File "/opt/anaconda3/envs/esoPy/lib/python3.7/site-packages/astroquery/query.py", line 225, in _request
        **req_kwargs)
      File "/opt/anaconda3/envs/esoPy/lib/python3.7/site-packages/astroquery/query.py", line 279, in _download_file
        length - existing_file_length,
    TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
    

So, any idea? and it always fails on the same file, although I can download the file from the web interface.

Cheers
Jorge

**Comment by jorgehumberto** [comment] 2019-02-22 16:13
hi,

To add some info to this: I have noticed that this genre of error occurs

**Comment by jorgehumberto** [comment] 2019-02-22 16:14
Sorry, closed by mistake.

**Comment by keflavich** [comment] 2019-02-22 16:15
I've tried exploring this a bit but I haven't reproduced it fully or had time to dig in in more detail.  I don't have any ideas yet.

**Comment by jorgehumberto** [comment] 2019-02-22 16:42
HI @keflavich 

Thanks for the update. 

Cheers
Jorge

**Comment by jwoillez** [comment] 2019-02-22 16:51
@jorgehumberto could you empty your cache and try again. I’ve notice that using the special access interface can cause issues like this. Your cache should be somewhere in ~/.astropy/cache/astroquery/eso

**Comment by jwoillez** [comment] 2019-02-22 16:55
@keflavich it may fail because the hash used for caching does not take into account the URL change. I should have a look into it. In general, it feels like the caching mechanism is only causing problems. What are your thought on this?

**Comment by keflavich** [comment] 2019-02-22 17:10
Generally I've been pretty happy with caching; it has enabled some use cases that are otherwise totally unavailable.  However, it is likely better to disable caching for data files (FITS files) by default, since they tend to cause problems and take a lot of space.  @bsipocz, let's talk more about this.

Why is the URL changing in this case?  I don't think we should cache data if the URL changes, unless it's a dynamically generated URL, then we should be sad.

**Comment by jorgehumberto** [comment] 2019-02-22 22:45
Hi @jwoillez 

> @jorgehumberto could you empty your cache and try again. I’ve notice that using the special access interface can cause issues like this. Your cache should be somewhere in ~/.astropy/cache/astroquery/eso

I already tried to clear the cache, to no avail.

I also had cases where the downloaded file was not a fits.Z file, but a bank login webpage, so I guess the connection somehow timed out? Is there any way to force a check to make sure the connection is still authenticated? of re-authenticate every XXX seconds or so?

Thanks
Jorge

**Comment by bsipocz** [comment] 2019-02-22 23:40
It would be weird if caching would cause this issue. Though the authentication approach may be a good one. We don't yet have the infrastructure to do the re-authentication but it would definitely be worth checking it.

**Comment by jorgehumberto** [comment] 2019-02-25 15:55
Hi,

I have more data that might help shed some light into this. On some cases (but no all) the files were not accessible on ESO's web interface (e.g., we got a permission denied message, although the account we're using has access to the same programme ID for other nights). But my guess is that it might be that those might be two different issues that throw the same error.

Is there a way to use the ' retrieve_data ' function to get the file list without downloading them and request number (basically building the datasets to makes sure no calibration file is forgotten)?

Cheers
Jorge

**Comment by jorgehumberto** [comment] 2019-02-27 14:59
Hi,

Ok, I think I might have found the problem. In several cases (cannot confirm that in all) the download fails for datasets that still show under construction on the ESO User Portal (different from the permission denied issue). Could it be that for some reason (i.e. timeout?) the connection is broken and the download fails? Does that make sense?

However, if I understood the function `retrieve_data` correctly, it only attempts to download the data once the `state` shows complete, correct? so in principle it should not fail...

Cheers
Jorge

**Comment by keflavich** [comment] 2019-02-27 16:25
Could you put a screenshot of what "under construction" looks like?  Is it possible that the ESO archive is reporting an incorrect state?

**Comment by FedorGetman** [comment] 2019-03-01 13:14
FYI: I can confirm the same error:
```
   length - existing_file_length,
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
with old historic system python installations (both 2.7 and 3.4). 
But fresh python (latest released tar downloaded from python.org; configure & make install; add pip & pip install astroquery) work perfectly with no error.

Seems something was different in http connection: "content-length" is not present in server response for old python instances, so "length" value doesn't  set up.

**Comment by jorgehumberto** [comment] 2019-03-06 16:13
hi @keflavich 

I am sorry, been unable to look into this earlier. We have found a permissions problem on the ESO side of things that causes some of the errors and are waiting on their answer (basically, the user has "apparently" all the permissions required to the programmes we are looking at but cannot download anything but calibrations).

At this moment I have found 3 occasions on which I get the above error:
- permissions to download the files are apparently correct on the User Portal, but user does not have access
- for datasets that take take too long to build, the connection drops and fails (can be replicated by downloading for example the SCIENCE files from night 2019-02-17 of ESPRESSO)
- downloading blocks of files with different ESO program IDs of which the user has no permissions for at least one of the programs.

Also, a different error occurs for large datasets, in which the connection drops and the downloaded files onwards are basically ESO's login page. This one is annoying, but can be easily bypassed by checking if any of the files that were downloaded are not *.fits.Z and if so re-download them.

As soon as I get more infor from ESO I'll post it here.

Cheers
Jorge

**Comment by keflavich** [comment] 2019-03-06 17:05
Thanks.  This sounds like it is mostly an ESO issue, not an astroquery issue, right?  i.e., there's nothing we could do about it if we want to?

**Comment by jorgehumberto** [comment] 2019-03-15 23:13
@keflavich 

Yes, I agree. I only have a couple of suggestions that I believe might help:
a) setting up a way to verify that the connection does not timeout from time to time (more difficult to implement), e.g. every 15/30 min;
b) adding an option to the 'retrieve_data' function so it will only download the list of files and request number instead of the files. This would allow to download the datasets at a later time without the need to make a new dataset request (useful in the case of timeouts)

Thank you for all the help!
Cheers,
jorge

**Comment by saimn** [comment] 2019-03-29 12:46
The timeout issue should be fixed by #1315. @jorgehumberto , did you try with the master branch or only with the latest release?

**Comment by jorgehumberto** [comment] 2019-04-03 11:08
HI @saimn 

I was using the latest release available on anaconda.

Cheers
Jorge

**Comment by bsipocz** [comment] 2019-04-03 18:16
Please try update then with `pip install --pre --upgrade astroquery`. For astroquery not all releases end up on conda-forge, at the moment better us the latest directly from PyPI.

**Comment by jorgehumberto** [comment] 2019-07-05 11:00
HI @bsipocz 
I am sorry, though I had answered this already. Upgrading with `pip` solved my problem, thanks!

Cheers
Jorge

**Closed** 2019-07-05 19:13 UTC
Labels: eso

**Comment by almicol** [comment] 2019-07-09 15:19
Hi, a couple of comments from the ESO side on all the above.

1) Many thanks to you all for using the ESO archive, and for your contributions in making easier to access it!

2) The eso astroquery package actually hardcodes various URLs in core.py which need to be change to fully support the special access case; so, using the suggested: 
Eso.QUERY_INSTRUMENT_URL = 'http://archive.eso.org/wdb/wdb/cas'
might not be enough (though I admit I have not tried to understand all repercussions there could be not fixing those URLs in the core.py).

3) Your constraint:
column_filters={'night':'2018-09-01', 'dp_cat':'SCIENCE'}
returns (among others) the file ESPRE.2018-09-05T18:26:46.039.fits.Z
which, as the filename says, belongs to a night that should not be returned by that constraint; so it seems to me that such filtering mechanism is not correctly implemented. The special access user interface, for that night and for the SCIENCE dp_cat returns only 3 files, all called ESPRE.2018-09-01T*.fits, while that column_filters constraint returns many more files (230!). 

4) I ran your code, using esocas, on that night, and downloaded 230 SCIENCE files (spanning from 2018-08-27 o 2018-09-09);
the mentioned file ESPRE.2018-09-05T18:26:46.039.fits.Z is indeed among them,
and it was downloaded without problems for my user account.
Two questions for you:
a.	Which one is your username?
b.	If you allow me, I can impersonate you and try to see if "you" have a problem downloading that file. Would you allow me to do that?

5)	I never got the error:
"TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'";
 I'm using python version : 3.7.3.final.0, could that be the reason?

6)	Regarding your comment: "permissions to download the files are apparently correct on the User Portal, but user does not have access": when you say "user does not have access", you mean that the user tries but gets a notification that the file is not accessible to her, or gets a different kind of error?  could you provide an example of that?

Many thanks!
Alberto (from the ESO Archive Science Group)

**Comment by jorgehumberto** [comment] 2019-08-20 15:19
Hi @almicol 

Sorry for the (extremely) late reply, I missed the notification email for this thread and only now saw your comment.

Now addressing some of your questions that I can answer:

> 3. Your constraint:
>    column_filters={'night':'2018-09-01', 'dp_cat':'SCIENCE'}
>    returns (among others) the file ESPRE.2018-09-05T18:26:46.039.fits.Z
>    which, as the filename says, belongs to a night that should not be returned by that constraint; so it seems to me that such filtering mechanism is not correctly implemented. The special access user interface, for that night and for the SCIENCE dp_cat returns only 3 files, all called ESPRE.2018-09-01T*.fits, while that column_filters constraint returns many more files (230!).

that is correct, I also have the same problem with other nights where files from wrong nights are also downloaded, or some calibrations are missing (e.g. 2018-10-27 which is missing DARK images)

@bsipocz , @saimn , any idea why that might happen?

> 4. I ran your code, using esocas, on that night, and downloaded 230 SCIENCE files (spanning from 2018-08-27 o 2018-09-09);
>    the mentioned file ESPRE.2018-09-05T18:26:46.039.fits.Z is indeed among them,
>    and it was downloaded without problems for my user account.
>    Two questions for you:
>    a.	Which one is your username?
>    b.	If you allow me, I can impersonate you and try to see if "you" have a problem downloading that file. Would you allow me to do that?

that particular file is no longer giving me problems (I assume from upgrading astroquery with pip?), but it looks that there are some issues with the way the file download list is being built. Similar to what happens to you, all looks fine when I use the ESO special access user interface.


> 5. I never got the error:
>    "TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'";
>    I'm using python version : 3.7.3.final.0, could that be the reason?

This error was fixed after upgrading astroquery with pip.  

> 6. Regarding your comment: "permissions to download the files are apparently correct on the User Portal, but user does not have access": when you say "user does not have access", you mean that the user tries but gets a notification that the file is not accessible to her, or gets a different kind of error?  could you provide an example of that?

Not sure what happened, but it looks that this was fixed after a few emails with someone on ESO's side (sorry, not sure who it was, it was done by someone else).

Thank you for your concern and thank you all for the help!

Cheers

**Comment by bsipocz** [comment] 2019-08-20 18:38
> I'm using python version : 3.7.3.final.0, could that be the reason?

@almicol - that's a particularly old version, I would suggest to upgrade your astroquery. Either now with `pip install --pre -U astroquery`, or wait a few days as we're about to do a new release this week.
